- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
When we connect to qpid, we need to ensure that we skip to the next SASL
mechanism if the current mechanism fails. Otherwise, we will keep retrying the
connection with a non-working mech.
This patch adds an additional string that is returned when PLAIN is not
available, but python-saslwrapper is installed.
> Add additional string to check for when connecting to qpid

- kombu/transport/SQS.py
This addresses #137 and reports like [this Stack Overflow question](http://stackoverflow.com/questions/17262958/celery-with-sqs-errors-in-logs).  I received similar errors occasionally while using the SQS transport with Celery.
My understanding of the reason for this problem is that SQS messages may be delivered twice, especially if you are polling frequently.  So that means the same delivery_tag UUID could be delivered to the same client in separate `boto.sqs.message.Message` instances.  This results in an error when acking the same delivery_tag twice (depending on whether the `kombu.transport.virtual:QoS._flush()` occurs between acks?), which raises a KeyError the second time (as reported above).  As a result the unacked duplicate message is actually left on the SQS queue until the …
> SQS: Set delivery tag to SQS message receipt handle

- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
The connection was never actually closed before, which wasn't good. This fixes it. I verified the fix against the reproducer script in celery/kombu#455
> Fixes close bug where the connection was not being closed

- kombu/message.py
In cases where a message is written to a log it is quite
useful to have the message format itself in a somewhat useful
format versus the default python ``repr`` which isn't quite useful.
This commit adds such useful ``__repr__`` and makes it so that it
returns a string that has some useful information about the
internals of the message (which can be handy when it is needed).
> Add a more useful message __repr__

- kombu/connection.py
Custom transport class that has `can_parse_url=False` is overrided in `params['transport']` with one that returns from `parse_url` call.
> Fix custom transport overriding

- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
https://github.com/celery/kombu/issues/476
errno = EBADF is raised when calling os.close() on an already closed file descriptor.
Thought hard about logging cases when the os.close() raised OSError with errno != EBADF but decided an invalid or already closed file descriptor is really the only reason the close() would fail.  So, in the interest of simplicity, I decided to just ignore it.
Also, base.Transport does not implement ```__del__()``` so did not do: super(Transport, self).```__del__()```.
> Fix #476, file descriptor leak in transport.qpid.Transport.

- docs/userguide/serialization.rst
if serializer is None and content_type is not specified, then serialization will happen (see messaging.Producer:_prepare)
> fix docs about content_type and serialization

- kombu/tests/transport/test_qpid.py
- kombu/tests/transport/test_redis.py
- kombu/transport/qpid.py
Fixes SASL mech selection to be from broker string
Also fixes some small test runner errors in qpid
and redis transport related to a newer version
of mock running on Travis.
Fixes #498
> Fixes SASL mech selection to be from broker string

- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
> Adds support, tests, and docs for login_method with Qpid transport.

- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
fixes celery/kombu#519
https://github.com/celery/kombu/issues/519
> Qpid transport can now connect as 'localhost'

- kombu/tests/transport/test_SQS.py
- requirements/test-ci3.txt
This is the only test failure for me under Python 3.x, and after applying this simple fix all tests passed here with Python 3.5. `boto` was added to test-ci3 to prevent it from happening in the future.
The master branch doesn't have the problem, though.
> Fix test_sqs for python 3.x

- kombu/async/aws/connection.py
There are 5 % with only 4 parameters, remove the surplus one.
> Remove surplus % from parameters of log.debug

- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
This was made possible thanks to a new callback that can
be registered with the Qpid messaging client 0.32+. The
necessary versions of those dependency libraries will be
available on PyPI soon.
closes celery/celery#2199
https://github.com/celery/celery/issues/2199
> Removes all threading usage from Qpid Transport code

- kombu/transport/qpid.py
Implements a workaround for celery/celery#3019
> @acks_late usage in Qpid Transport now acks all messages

- kombu/tests/transport/test_qpid.py
- kombu/transport/qpid.py
> Switches delivery_tag to uuid.uuid4() for Qpid transport

- kombu/transport/redis.py
I have a bug similar to celery/celery#2903 when trying to connect to a redis broker via a unix domain socket:
```
File "/usr/local/lib/python3.4/dist-packages/celery/worker/__init__.py", line 206, in start
self.blueprint.start(self)
File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 123, in start
step.start(parent)
File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 374, in start
return self.obj.start()
File "/usr/local/lib/python3.4/dist-packages/celery/worker/consumer.py", line 279, in start
blueprint.start(self)
File "/usr/local/lib/python3.4/dist-packages/celery/bootsteps.py", line 123, in start
step.start(parent)
File "/usr/local/lib/python3.4/dist-packages/celery/worker/consumer.py", line 479, in start …
```
> Fixed TypeError when conneting to redis via unix domain socket

- Changelog
- README.rst
- docs/includes/introduction.txt
- kombu/__init__.py
- kombu/transport/zookeeper.py
As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- kombu/tests/transport/test_qpid.py
The Qpid tests were mocking pipe and fcntl and this
was causing a strange behavior with nose. When I
would run `nosetests` not all unit tests would run.
By removing these three tests we don't loose much
in test coverage and lots of other tests now run.
> Removes some Qpid tests causing other test skips

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Fixes celery/kombu#628
**Root cause:**
- setting `connparams[‘ssl’] = True` will cause an unexpected keyword
exception when initializing a redis `Connection` or `SSLConnection`
- connection_class must be `redis.SSLConnection`. The base `redis.Connection`
class does not support SSL parameters.
**Notes:**
- Updated the comment and tests to reflect the required format since it
is different than amqplib. Ideally the Celery documentation that talks about `BROKER_USE_SSL` should be updated to specify the keyname format for redis vs amqplib.
- If you attempt to use Redis-over-SSL as both a transport and results backend then Celery will fail since the `RedisBackend.connparams` are not patched to support SSL. These end up passed directly into `redis.ConnectionPool` which defaults to the base …
> Fix Redis SSL support

- examples/rpc-tut6/rpc_client.py
There is an error in the RPC example that is causing [this](https://github.com/celery/kombu/issues/639) issue.
> Fixed rpc example

- kombu/transport/librabbitmq.py
Error message:
```[2016-11-11 10:05:16,683: CRITICAL/MainProcess] Unrecoverable error: TypeError("__init__() got multiple values for keyword argument 'body'",)
File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 203, in start
self.blueprint.start(self)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
step.start(parent)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 370, in start
return self.obj.start()
File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
blueprint.start(self)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
step.start(parent)
File …
```
> Fixed wrong keyword argument `channel`

- kombu/transport/mongodb.py
I am no mongodb specialist, but there is an explicit mentioning in MongoDb docs about natural sorting:
"Queries that include a sort by $natural order do not use indexes to fulfill the query predicate"
https://docs.mongodb.com/v3.2/reference/method/cursor.sort/#index-use
So as far as we have "query" index set in ensure_indexes, so this will not be used according to the docs.
> remove natural sort

- kombu/transport/qpid.py
The \_\_init\_\_ function calls verify_runtime_environment before setting
the use_async_interface variable.  If it throws an exception in that
function, the \_\_del\_\_ method will be called, and raises an
AttributeError
using getattr in the __del__ method to guard against this
> Switch to using getattr in qpid.Transport.__del__

- t/unit/transport/test_SQS.py
This one-liner fixes some tests when run under Python 3.  The filter() method returns an iterator now.
> Fix a broken test in python 3

- kombu/transport/etcd.py
``EtcdException`` is the propler exception class to catch since ``EtcdError`` is subclassed from ``object``.
> etcd: Replace EtcdError with EtcdException

- kombu/transport/qpid.py
Celery 4.0.2 passes the `multiple` keyword argument to `basic_ack`.
This did not used to occur with 3.1.20- so this change is only being
merged into the 4.0 branch. The desired functionality of this param is
documented here [0], but the Qpid transport uses UUIDs as the
delivery_tags so we don't have a record of the sequential messages
required to implement this. We use UUIDs as the deliver_tag to avoid
Issue #563.
With the functionality for the `multiple` parameter not implemented, an
AssertionError is raised if Celery attempts to meaningfully use the
`multiple` parameter with the Qpid transport. A developer or user who
encounters this AssertionError should file a bug with Kombu.
[0] http://amqp.readthedocs.io/en/latest/reference/amqp.connection.html#amqp.connection.Connection.Channel.basi …
> Adds `multiple` kwarg to Qpid `Channel.basic_ack`

- .gitignore
- AUTHORS
- kombu/transport/zookeeper.py
- setup.py
- t/unit/transport/test_zookeeper.py
- tox.ini
Using Python 3 delaying a task with ZooKeeper as a broker fails with `TypeError: value must be a byte string` because [kazoo.Queue.put()](https://github.com/python-zk/kazoo/blob/8f6bf35d/kazoo/recipe/queue.py#L111) requires `value` argument to be a byte string .
I just add forced message conversion to bytes.
Will be thankful if anybody helps me with writing a test for it.
> Fix byte string for kazoo.Queue in Python 3

- kombu/transport/SQS.py
- requirements/funtest.txt
- t/unit/transport/test_SQS.py
Related Pull Requests:
- #693 
- #714
> Allow endpoint URL to be specified for SQS transport

- kombu/compat.py
Removes warning during tests:
DeprecationWarning: generator '...' raised StopIteration
For additional information, see:
- https://docs.python.org/3/whatsnew/3.5.html#pep-479-change-stopiteration-handling-inside-generators
- https://www.python.org/dev/peps/pep-0479/
> Remove deprecated use of StopIteration in generators

- kombu/transport/virtual/exchange.py
Fixes the following warning when running tests on Python 3.6:
DeprecationWarning: invalid escape sequence \.
> Fix invalid escape sequence

- kombu/messaging.py
https://github.com/celery/kombu/issues/690
Add self.channel.connection check to prevent AttributeError.
Tested with this gist
https://gist.github.com/eavictor/ee7856581619ac60643b57987b7ed580
> Fix  Closed connection and with statement blows up

- kombu/transport/zookeeper.py
- t/unit/transport/test_zookeeper.py
Noticed that kombu removes last chroot character.
For example, you connect to ZooKeeper with chroot `/project` but celery produces/consumes tasks with chroot `/projec`.
> Fix last chroot character trimming for ZooKeeper

- kombu/common.py
- t/unit/test_common.py
uuid3() uses md5, which is disallowed on systems running in FIPS mode
(http://csrc.nist.gov/groups/STM/cavp/validation.html)
> Use uuid5() as an option in generate_oid if uuid3 fails.

- kombu/connection.py
- requirements/pkgutils.txt
Fixes https://github.com/celery/celery/issues/3921 .
> Use ensure_connection to allow broker failover

- AUTHORS
- kombu/transport/librabbitmq.py
I know that librabbitmq support in 4.x is spotty and that it is kind of no longer supported. But it works just fine (at least with python 2.7) with task_protocol=1 except for one thing - transient queues mess rabbitmq up.
librabbitmq doesn't really handle utf8 very well and creating queues with unicode arguments result in getting 500 error when listing queues in rabbitmq:
http://localhost:15672/#/queues in management plugin
and same for API.
Relevant issues I found:
https://github.com/mher/flower/issues/661
https://github.com/rabbitmq/rabbitmq-management/issues/332
Converting keys to bytestring fixes it.
> Fix librabbitmq queue handling

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
Commit [`cdbfe9a64e1884dc99fc9806a834f23cf8398a3b`](https://github.com/celery/kombu/commit/cdbfe9a64e1884dc99fc9806a834f23cf8398a3b#diff-3cc1ff6df0f488077057a603b8f5e5d4R487) added tooling to retrieve the `hostname` from the SQS Transport.  If no hostname is provided (for example, if you only configure an app with `broker_transport = 'sqs'`), the hostname is [set to a default value](https://github.com/alukach/kombu/blob/0c20e84c63489b6efb2dd93f607e00fcec6f0597/kombu/connection.py#L585-L599) from the Transport baseclass' [`default_connection_params` property](https://github.com/alukach/kombu/blob/0c20e84c63489b6efb2dd93f607e00fcec6f0597/kombu/transport/virtual/base.py#L1002-L1003).  This is problematic, as the default is `'localhost'`, which is likely not correct for an SQS queue and …
> Prevent SQS from defaulting to localhost hostname

- .gitignore
- .landscape.yml
- docs/reference/index.rst
- docs/reference/kombu.transport.SLMQ.rst
- docs/reference/kombu.transport.sqlalchemy.models.rst
- docs/reference/kombu.transport.sqlalchemy.rst
- kombu/transport/__init__.py
- kombu/transport/etcd.py
- kombu/transport/sqlalchemy/__init__.py
- kombu/transport/sqlalchemy/models.py
- requirements/extras/sqlalchemy.txt
- requirements/test-ci.txt
- setup.py
- t/integration/tests/test_sqla.py
- t/unit/transport/test_sqlalchemy.py
Support for sqlalchemy transport was removed in 4. This is needed by celery which is used by Airflow. Not having it breaks Airflow. I tested this manually and it works.
> Re-Adding support for sqlalchemy as it is needed by Apache project Airflow

- kombu/entity.py
The linked document was the first result on Google for the title of the link.
I'm not sure how the nice title for the replaced link was created (there's another bit.ly link with a hashed string pointing to Wikipedia).
> Fixed broken link to AMQP documentation

- Changelog
- kombu/transport/mongodb.py
- t/unit/transport/test_mongodb.py
Since pymongo v3.0 it changed the way it parses readpreference uri option. There is kind of bug in that option validator, as it returns result that is not valid for same validator (It returns the index of mongos mode in the [_MONGOS_MODES](https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/read_preferences.py#L33) tuple. If you try to use the returned value as a keyword argument for `MongoClient`, it will fail with an exception:
```
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/base.py", line 923, in create_channel
channel = self.Channel(connection)
File "/usr/local/lib/python2.7/dist-packages/kombu/transport/mongodb.py", line 118, in __init__
self.client
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
value …
```
> Fix readpreference option parsing in MongoDB transport

- Changelog
- kombu/async/hub.py
- t/unit/async/test_hub.py
fixes https://github.com/celery/celery/issues/3712 
Before handling the todo items we "freeze" them by copying them aside and clearing the list.
This way if an item in the todo list appends a new callable to the list itself it will be taken care of in the next iteration of the parent loop instead of producing an infinite loop by adding it to the list we're running on.
> Fix infinite loop in create_loop

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
This PR contains three bugfixes for the SQS transport:
* The `_get_bulk` and `_get` methods should take advantage of long-polling.
* I was running into an error where `resp['Messages']` would throw a `KeyError`. Admittedly, I don't recall exactly what situation this occurred during, I believe that it was when using a Kombu Consumer to read off of a queue with non-celery messages.  Nonetheless, I believe using `resp.get('Messages')` should have no negative effect to current operation but grant more flexibility to SQS message format.  If someone feels like this flexibility is a bad idea, let me know and I can attempt to recreate how I was running into the `KeyError`.
* The `_get` method fails as `receive_message` on the `Boto3` session expects only keyword arguments.
> Fix SQS requests and response handling

- Changelog
Noticed that the [build on `master` is failing](). I've tried to fix the Changelog to resolve the issues (and additionally ensure that all changes were in the past-tense to fit pre-existing style).  I'm unsure how to resolve the issue:
> `Changelog:17: WARNING: Inline emphasis start-string without end-string.`
Line 17 does not appear to be missing the end-string:
> `     Contributed by **Anthony Lukach**.`
> Cleanup Changelog (resolve failing build)

- kombu/transport/redis.py
service_name is not used anymore, and was changed in this commit: a46dba8f2e3490e6c30ca24cf6ee4a96b7f4124a
> fix(doc): updating pydoc for redis sentinel

- Changelog
- kombu/connection.py
- t/unit/test_connection.py
Not sure if this is the best implementation, however it gets the job done for my needs. My goal is to be able to start my application when the message broker is offline. Upon startup, the application attempts to establish queues, which requires the `Channel.default_connection` to be generated. When generating the `default_channel`, `Channel.ensure_connection` with no `max_retry` (or other options) provided. This caused the application to hang while infinitely attempting to connect to the broker.
Fixes #765
> Pass connection options from broker_options to default_channel 

- kombu/transport/SQS.py
Invalid indent was fixed. It causes 'reference before assignment' error since https://github.com/celery/kombu/commit/e9bf18994fa9565e2968287726381009f0127754
> Invalid indent fixes.

- README.rst
- docs/reference/kombu.serialization.rst
- docs/userguide/serialization.rst
This forwards automatically to the newest Python source, i.e., 3.6. 2.6 is not supported anymore (although it was introduced in 2.6, I've noticed), so I replaced it with 2.7.
`Python 2.7+`: https://docs.python.org/library/json.html
`apicheck` fails both locally, and remote. I'm not sure how to fix that.
> Update links in documentation to either https or to new locations

- kombu/transport/qpid.py
- t/unit/transport/test_qpid.py
We are seeing messages disappear in durable queues when restarting
qpid. This coincides with the rabbitmq code (e.g. https://git.io/v7jNV).
> Make messages durable by default in qpid

- docs/userguide/producers.rst
- kombu/compat.py
- kombu/connection.py
- kombu/simple.py
- kombu/utils/functional.py
I added a comment in `kombu/connection.py`. I noticed a lot of unused parameters in functions and methods, and in a few cases the index-variable `i` in for-loops could be replaced with `_`.
> Removed some unnecessary variable assignments

- kombu/utils/json.py
Some environments bundle versions of simplejson that do not have
JSONDecodeError. Would like to handle ImportErrors in these cases.
> Update json utils.

- kombu/async/timer.py
PR for [issue #820 ](https://github.com/celery/kombu/issues/820).
Closes #820.
> Fix typo with Timer's docstring

- kombu/transport/SQS.py
- kombu/utils/encoding.py
- t/unit/utils/test_encoding.py
This change alters the safe_str() function to handle the case when a python-future package "newstr" and "newbytes" are being used in Python 2.7
> Fixes #791 - SQS queue name gets mangled in Python 2.7 environment

- kombu/resource.py
- t/unit/test_pools.py
`Resource.resize()` raises an exception if the pool is in use and the new size is smaller than the old size. However, it also raises this exception when the new size is zero, which should correspond to disabling the pool. Instead of shrinking the pool to zero and releasing all resources, we can simply dequeue all resources and forget about them.
Refs #781
> Prevent spurious exception on Resource.resize(0)

- kombu/transport/librabbitmq.py
- t/unit/transport/test_librabbitmq.py
Hi, I believe this will solve #860. Because librabbitmq connection's fileno method will raise `ValueError` (https://github.com/celery/librabbitmq/issues/39) if the socket has unexpected been closed, this was escaping being caught when running `os.close`, preventing publish connection retries if the socket disappeared.
Closes #860.
> Handle librabbitmq fileno socket not connected raising ValueError

- README.rst
- docs/includes/introduction.txt
- docs/reference/kombu.serialization.rst
- docs/templates/readme.txt
- kombu/compat.py
- kombu/transport/qpid.py
- setup.py
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
> Update all pypi.python.org URLs to pypi.org

- kombu/transport/librabbitmq.py
we couldn't find `https://pypi.python.org/librabbitmq/`  on pypi, and i modify it to `https://pypi.python.org/pypi/librabbitmq/`
> fix librabbitmq link error

- kombu/entity.py
- t/unit/test_entity.py
Queues that are declared with a TTL should also be excluded from the cache in case they expire between publishes on the same channel.
> don't cache declaration of expiring queues

- kombu/connection.py
- kombu/utils/functional.py
- t/unit/utils/test_functional.py
* Feature: add parameter `timeout` to `retry_over_time`
then we can add timeout option when connecting broker.
> Add parameter timeout to retry_over_time

- kombu/asynchronous/hub.py
- kombu/transport/redis.py
- t/unit/asynchronous/test_hub.py
The actual version does not allow `celery.bin.celery.main` to run, raise a SystemExit, catch it and then run again. (See: https://github.com/alanjds/celery-serverless/commit/a23f79d3cfe17ed8a91003707af4a5dd1e2aa542#diff-b4826aeb276ca699cf1adda1903fe3eaR55)
To allow it, the `kombu.async.hub.Hub.poller` became a @property that regenerates on access. And the Redis backend tries to recreate it before acessing, if needed.
Indeed, `celery.worker.state.should_{stop,terminate}` should be reset after every SystemExit for it to work, but this part is a patch not for Kombu repo ;) .
(See: https://github.com/alanjds/celery-serverless/commit/a23f79d3cfe17ed8a91003707af4a5dd1e2aa542#diff-b4826aeb276ca699cf1adda1903fe3eaR57)
> "Reentrant" version, that allows a `celery.bin.celery.main` worker to run multiple times

- kombu/entity.py
- t/unit/test_entity.py
To fit with the documentation, Queue can now handle a str argument for
the exchange parameter in the constructor, as well as an actual Exchange
object.
Added relevant unit tests to avoid regressions.
Fixes: https://github.com/celery/kombu/issues/903
Signed-off-by: Antonio Gutierrez <chibby0ne@gmail.com>
> Queue: add handling of Exchange as str to constructor

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
**Problem**
1. Create new job with acks_late flag as True
2. Use gevent and patch it using monkey.patch_all()
3. Execute the task
4. While task is executed (and visibility_timeout is far from expiry) kill the worker
5. Task is not re-executed after new worker is initiated
**What was done**
When worker start (patched with gevent) restore all unacked messages 
issue:
https://github.com/celery/celery/issues/4976
> on worker restart - restore visible regardless to time

- kombu/connection.py
- kombu/simple.py
- t/unit/test_simple.py
Update simple.py so SimpleQueue can pass queue_arguments to the created Queue object.
This will allow SimpleQueue to connect to RabbitMQ's  lazy queues (afaik), i.e., 'x-queue-mode' is set to 'lazy'.
> Allow SimpleQueue to pass 'queue_arguments' to Queue object.

- .travis.yml
- requirements/docs.txt
- requirements/test-ci.txt
- tox.ini
I also installed more of our dependencies so we'll skip less tests.
Currently the pymongo and etcd tests are broken.
We should fix them but in the meanwhile, we'll continue to skip them.
> Added Python 3.7 to the build matrix

- kombu/connection.py
- kombu/transport/__init__.py
- t/unit/transport/test_redis.py
Putting a 'rediss'-specific check into a generic connection module feels
like a code smell but there doesn't appear to be another way to intercept
the connection initiation code. It defaults to the least secure form, as
there is no suitable default location for `ca_certs`. The recommendation
would still be to follow the documentation and specify `broker_use_ssl` if
coming from celery.
https://github.com/celery/kombu/issues/862
> Add support for 'rediss' scheme for secure redis connections.

- .coveragerc
- docs/includes/introduction.txt
- docs/reference/index.rst
- docs/reference/kombu.transport.azureservicebus.rst
- docs/reference/kombu.transport.azurestoragequeues.rst
- kombu/transport/__init__.py
- kombu/transport/azureservicebus.py
- kombu/transport/azurestoragequeues.py
- requirements/extras/azureservicebus.txt
- requirements/extras/azurestoragequeues.txt
- requirements/test-ci.txt
- setup.py
- t/integration/tests/test_azureservicebus.py
- t/integration/tests/test_azurestoragequeues.py
This pull request adds two new transport implementations:
- `azurestoragequeues` is implemented on top of [Azure Storage Queues](https://azure.microsoft.com/en-us/services/storage/queues/). This offers a simple but scalable and low-cost PaaS transport for Celery users in Azure. The transport is intended to be used in conjunction with the [Azure Block Blob Storage backend](https://github.com/celery/celery/pull/4685).
- `azureservicebus` is implemented on top of [Azure Service Bus](https://azure.microsoft.com/en-us/services/service-bus/) and offers PaaS support for more demanding Celery workloads in Azure. The transport is intended to be used in conjunction with the [Azure CosmosDB backend](https://github.com/celery/celery/pull/4720).
This pull request was created together with @ankurokok, …
> Add transports based on Azure PaaS

- kombu/transport/qpid.py
As spelled on https://pypi.org/.
> Correct capitalization of PyPI

- AUTHORS
- kombu/common.py
- kombu/connection.py
- kombu/transport/etcd.py
- kombu/transport/virtual/base.py
- t/unit/test_common.py
This fixes a deprecation warning from the standard library's logging module:
> The 'warn' method is deprecated, use 'warning' instead
> Fix a deprecation warning about logger.warn()

- kombu/asynchronous/hub.py
- t/unit/asynchronous/test_hub.py
We have problem with hanged workers (and SQS queue).
Unfortunately - #760 is not quite enough to fix infinite loop. Consider this scenario:
1. Take first item from todo
2. Item schedules itself back to self._ready and gets to the front
3. Since todo is reference to self._ready, `pop` takes it again => goto 1.
Fixes #685
> Fix infinity loop in create_loop

- README.rst
The link in the README to kombu.me is broken (#930). This PR replaces the broken link with a link to the documentation.
> Replace README web link with link to documentation

- kombu/compression.py
- setup.cfg
- t/unit/test_compression.py
This appears to have been resolved. The touched lines were from 2011, and the satus of the buf changed in 2013. I didn't check on Jython, my suggestion is only based on that report.
http://bugs.jython.org/issue1445
> Removed Jython bz2 import fallback

- kombu/messaging.py
Fixes #940 - this is a very minor docstring change. I just wanted to fix all the warnings that occur when building the Celery docs. I've noticed a similar set of issues with the Kombu docs and, unless you want me to stop, I would be happy to fix those as well when I have a chance.
> disambiguate docstring typehints causing warnings building celery docs

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Further to #946 this fixes the underlying issue in a easy-to-upgrade way for end users, many of whom will have redis installed via other means. By having this check here and supporting both versions concurrently it makes it easier for end users, and to use celery/kombu in projects that use redis elsewhere.
With this change it is possibly worth reverting #946
> Support redis-py v2 and v3

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
Implements a fix for #950, slightly different from the original proposal.
I did that because the boto3 library could be missing. I'm guessing, from the guard condition at the constructor:
```
def __init__(self, *args, **kwargs):
if boto3 is None:
raise ImportError('boto3 is not installed')
super(Channel, self).__init__(*args, **kwargs)
```
So I couldn't just use boto3 in the class definition to override the default region.
Instead I think it's better to just put it as a default with higher precedence than the current default region.
> Add boto3 default region before hardcoded default

- kombu/transport/redis.py
This fixes celery/celery#3898 issue.
As far as I understand the celery hang is happening under the following scenario:
* redis connection is created in main thread;
* then, process forks a worker and it receives copies of all open sockets
* when the worker is done (`max_tasks_per_child`) it cleans up its resources (closes connections)
* redis-py client closes its socket in connection,
however before `close()` it calls `shutdown()` which shuts down all copies of socket shared
between all the processes
So, again, if I understand all correctly, main process is still able to read that socket and poll always
returns it as ready however it is in unoperational state.
> Fix Redis disconnect handling

- Changelog
- README.rst
- docs/includes/introduction.txt
- docs/reference/kombu.transport.pyro.rst
- docs/userguide/connections.rst
- kombu/transport/__init__.py
- kombu/transport/pyro.py
- requirements/test.txt
- t/unit/transport/test_pyro.py
I'm trying to get the Pyro transport working for Kombu.
A few minor changes were needed in the transport itself to be compatible with recent Pyro versions again, but I struggle with understanding the following:
Where is the pyro broker component that should  provide the actual queueing methods that are remotely accessed from the Pyro transport? I see nothing in the kombu repo doing this, and can't find anything via google.  Is there such a thing or should I write it myself?
> Making the pyro transport available, fix it for recent Pyro4 versions, add broker daemon

- kombu/transport/SQS.py
Not all AWS SQS messages have base64 encoded message body. For example, a S3 event derived SQS message has a `Body` as an unencoded JSON string.
> handling non-base64-encoded SQS message

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
These were the exceptions seen. Redis Sentinel worked only if the first node's sentinel service in the URI was up. A server outage would have caused downtime.
```
[2017-11-14 16:47:57,860: INFO/Beat] beat: Starting...
[2017-11-14 16:47:57,865: ERROR/MainProcess] consumer: Cannot connect to sentinel://10.0.0.10:26379/0: No master found for 'mymaster'.
Will retry using next failover.
[2017-11-14 16:47:57,883: INFO/MainProcess] Connected to sentinel://10.0.0.11:26379/0
[2017-11-14 16:47:57,896: ERROR/MainProcess] consumer: Cannot connect to sentinel://10.0.0.10:26379/0: No master found for 'mymaster'.
Will retry using next failover.
[2017-11-14 16:47:57,918: INFO/MainProcess] mingle: searching for neighbors
[2017-11-14 16:47:57,942: WARNING/MainProcess] consumer: Connection to broker lost. …
```
>  Moving the handling of Sentinel failures to the redis library itself. 

- kombu/utils/encoding.py
When we were using celery , and using `pickle` format to transfer a bytes variable like a file content, for example a picture file, then we will get an exception here. 
```
File "/Users/daiyue/git/hxtsaas/env/lib/python3.6/site-packages/celery/app/trace.py", line 436, in trace_task
Rstr = saferepr(R, resultrepr_maxsize)
File "/Users/daiyue/git/hxtsaas/env/lib/python3.6/site-packages/celery/utils/saferepr.py", line 74, in saferepr
o, maxlen=maxlen, maxlevels=maxlevels, seen=seen
File "/Users/daiyue/git/hxtsaas/env/lib/python3.6/site-packages/celery/utils/saferepr.py", line 118, in _saferepr
val = "b'%s'" % (bytes_to_str(truncate_bytes(val, maxlen)),)
File "/Users/daiyue/git/hxtsaas/env/lib/python3.6/site-packages/kombu/utils/encoding.py", line 58, in …
```
> fix bytes_to_str bug

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
This is useful for setting encryption options on AWS SQS queue creation. 
This implements a general solution, when new features are added to queues, clients using Kombu can just specify additional transport_options.
Fixes #958
> Allow setting boto3.sqs.create_queue Attributes via transport_options

- t/unit/transport/test_pyamqp.py
Failing unittests were caused by PR https://github.com/celery/py-amqp/pull/221.
> Fix failing unittests of pyamqp transport.

- kombu/asynchronous/hub.py
According to [PEP-479](https://www.python.org/dev/peps/pep-0479/) StopIteration should not be used any more to indicate the termination of a generator.
Starting from Python 3.7 this behaviour is always enforced and a RuntimeError is raised instead.
We now return instead of raising StopIteration.
> Avoid raising StopIterator in generators

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
A more conservative take on https://github.com/celery/kombu/pull/887 + tests.
Fixes #888.
> SQS: fix trimming .fifo from queue name

- kombu/compression.py
- requirements/extras/lzma.txt
- requirements/test-ci-py2.txt
- t/unit/test_compression.py
LZMA has been available since Python 3.3.
This PR introduces LZMA compression support for tasks.
In addition, we also support using the backported version for Python 2.7.
> Added support for lzma compression

- kombu/compression.py
- requirements/extras/zstd.txt
- requirements/test-ci.txt
- t/unit/test_compression.py
> Zstandard, or zstd as short version, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios. It's backed by a very fast entropy stage, provided by Huff0 and FSE library.
We now allow users to install the python bindings to zstd and compress tasks using the zstd algorithm.
> Added optional support for zstd compression

- kombu/utils/functional.py
- kombu/utils/url.py
- t/unit/transport/test_qpid.py
I got the deprecation warnings about the abstract base classes from the collections module:
```
/kombu/kombu/utils/functional.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Iterable, Mapping, OrderedDict
```
it seems like an easy fix, so I just went ahead and did it.
> import collections.ABCs from correct module

- kombu/transport/azureservicebus.py
The Azure ServiceBus SDK upgrade from version 0.21.1 to 0.50.0 introduced a breaking change which affects the `azureservicebus://` transport. This pull request makes kombu compatible with both old and new versions of the SDK. See [the Azure ServiceBus SDK release notes](https://github.com/Azure/azure-sdk-for-python/tree/97b71f2670fe3ebffd4c834c8d7681284d02e048/azure-servicebus#migration-from-0211-to-0500) for more background.
> Fix breaking change in Azure ServiceBus SDK

- kombu/log.py
I noticed that  `DISABLE_TRACEBACKS` env variables wasn't always respected by the logger.
For example in `kombu\mixin.py` (line 56) with this kind of code:
```python
def on_connection_error(self, exc, interval):
warn(W_CONN_ERROR, interval, exc, exc_info=1)
```
Debug, info and warn logger level weren't tested about the `DISABLE_TRACEBACKS` settings and now are to provide a way to disable traceback(s) printing or file-logging.
This change should not change the default behavior of log/logger unless the `DISABLE_TRACEBACKS` env variable is set.
> Traceback can be disabled for all log levels

- kombu/resource.py
As documented in https://github.com/celery/kombu/issues/741 and https://github.com/eventlet/eventlet/issues/415 there is a mismatch between the monkey-patched eventlet queue and the interface kombu is expecting. This causes celery to crash when the `broker_pool_limit` config option is set. https://github.com/eventlet/eventlet/issues/415 suggests that the mutex can be a noop and all will be fine, so that's what I've done here.
As a side note, I can't get the tests to run for me locally, and there isn't much of a `Here's how to get started contributing to kombu` section. Maybe that's something to consider?
> Allow mutex to be noop for eventlet

- kombu/compression.py
- t/unit/test_compression.py
This was removed in #938 due to assumption that it only affected Jython but
the condition can be present in systems built without bz2 support.
Not sure if this is a system configuration the project wants to support but systems without bz2 work with 4.2.2 and fail with 4.3.0.
This is essentially a rollback of the #938
> Restore bz2 import checks in compression.py

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
The problem is that `self.connection.client.alt` is only populated when there's more than one client URL provided, e.g. `"sentinel://foo;sentinel://bar"`. It will also always contain all URLs, including the primary/first entry.
So if the `alt` list is empty, it (usually) means there was only one client URL provided.
I also took the liberty to perform name and type changes to be more in line with the examples and documentation in the `redis` library. The argument is `sentinels`, not `connection_list`. And it's of the type `List[Tuple[str, int]]`, not `List[List[str, str]]`.
Fixes #1004
> Handle the case when only one Redis Sentinel node is provided

- kombu/utils/url.py
- t/unit/utils/test_url.py
If you use the `rediss://` protocol as recommended in Celery:
```
result_backend = 'rediss://:password@host:port/db?\
ssl_cert_reqs=CERT_REQUIRED\
&ssl_ca_certs=%2Fvar%2Fssl%2Fmyca.pem\                  # /var/ssl/myca.pem
&ssl_certfile=%2Fvar%2Fssl%2Fredis-server-cert.pem\     # /var/ssl/redis-server-cert.pem
&ssl_keyfile=%2Fvar%2Fssl%2Fprivate%2Fworker-key.pem'   # /var/ssl/private/worker-key.pem
```
http://docs.celeryproject.org/en/latest/userguide/configuration.html#configuring-the-backend-url
The URL does not get initialized with the correct SSL parameters.
I added some extra logic in the URL parser to extract SSL parameters and pass them through correctly.
> Support SSL URL parameters correctly for rediss protocol

- kombu/transport/qpid.py
- t/unit/transport/test_qpid.py
qpid transport supports an async interface, but this wasn't declared
properly. It was missing an appropriate 'implements' class property.
This seems to have been missed because:
- kombu 4.x was branched from 3.0.21
- qpid transport was originally added after that in 3.0.24
- Transport.implements was added in commit 6a1abb7e9 on the 4.x branch
only, before the qpid transport was in that branch
- qpid transport code was then copied between 3.x and 4.x branches but
addition of Transport.implements was missed.
> qpid: correctly declare support for async event loop

- kombu/transport/qpid.py
- t/unit/transport/test_qpid.py
This is a follow-up to ddba8aeaf0f68. Prior to that commit,
"implements" was missing entirely for qpid. The earlier commit
added it, but only declared that the transport was async-capable.
Turns out it's important also to declare the supported exchange
types. In particular, if the transport doesn't declare support
for the 'fanout' exchange type, pidbox wouldn't be used[1] and so
it would still not be possible to revoke a task with terminate=True
when using the qpid transport.
[1] https://github.com/celery/celery/commit/2f58c35340f648
> qpid: ensure supported exchange types are declared

- kombu/transport/librabbitmq.py
Since we attempt to serialize the priority property if it exists in the dictionary (See https://github.com/celery/librabbitmq/blob/3fa1d38c4e66e6efdbdc7d584abe0a59857bef29/Modules/_librabbitmq/connection.c#L739) it must be an integer.
Fixes celery/celery#5340.
> Include priority in properties only if it's not None

- kombu/transport/memory.py
- t/unit/transport/test_memory.py
Part of https://github.com/celery/kombu/issues/1050, with this fix
the function does not raise the exception.
The init `defaultdict(set)` is the same init from amqp lib.
> Add events field on memory channel

- kombu/serialization.py
The build from Celery is broken (see https://github.com/celery/celery/issues/5555) because one test tries to enable all serializers by calling disable_insecure_serializers(allowed=None), but because `None` is the default value, it fallbacks to the default behaviour.
Using a [sentinel value](https://treyhunner.com/2019/03/unique-and-sentinel-values-in-python/) as default instead of `None` should fix this.
Fixes https://github.com/celery/celery/issues/5555
> Use a sentinel value to fix Celery's build

- .travis.yml
- kombu/serialization.py
- kombu/utils/uuid.py
- requirements/default.txt
Use FastUUID when possible.
FastUUID provides bindings to Rust's UUID library.
It is much faster and I wrote the bindings so I know they are production ready.
> Use fastuuid on CPython>=3.5

- .travis.yml
- kombu/serialization.py
- tox.ini
Flake8 doesn't pass on Python 3.6 due to some keyword left for Python 2 compat, will have to wait for when Python 2 is dropped (#990)
> Fix broken build steps

- kombu/connection.py
- t/unit/test_connection.py
Prior to this change, one needed to specify a URL using a URI
identifier, e.g., `pyamqp://foo.bar`. This change makes it so calling
`.switch(..)` again results in switching the host, not switching the
resource identifier.
This simplifies setting up connections with just hostnames specifying
the resource identifier once, separately.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
> Allow users to switch URLs while omitting the resource identifier

- kombu/common.py
- t/unit/test_common.py
I was studying this recent issue https://github.com/celery/kombu/issues/1045 and how it related to the change merged here:  https://github.com/celery/kombu/pull/779/files
I think the spirit of change in that prior kombu PR is good from @tyarimi, but the Entity (Exchange or Queue or ...) must be bound before calling entity.channel.connection.client.ensure as it was before.
My Change here factors out the logic that ensures it is bound so that it can be reused.  Since I was adjusting that code, I updated the two asserts in the file to not be asserts because I learned at Pycon that production code should not use asserts since they can be stripped out in optimize and other things, it is better to make logical checks and raise appropriate exceptions.   Asserts are good for unit tests and other …
> Issue 129 fix maybe declare

- Changelog
- kombu/utils/compat.py
- requirements/default.txt
- t/unit/utils/test_compat.py
See e.g. https://github.com/pypa/setuptools/issues/510#issuecomment-463667124
On a moderatly large project (~200 installed packages) at $work this saves ~150 ms on
`python -c 'from kombu import Exchange'`
> Switch from pkg_resources importlib-metadata

- kombu/utils/functional.py
- t/unit/utils/test_functional.py
When max_retries=0, it should not retry at all instead of retrying infinitely. See #1079
> Make sure that max_retries=0 is treated differently than None

- .coveragerc
- kombu/transport/azureservicebus.py
- t/unit/transport/test_azureservicebus.py
This PR adds `wait_timeout_seconds` to be used to receive queue message when timeout isn't informed  and can be set using `broker_transport_options`
> Add wait timeout settings to receive queue message

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Hello,
This PR fixes #659.
The root cause of the issue is that the connection can be erased during an execution of `self._receive_one(c)`.
So `c.connection` should be checked before every iteration, not only before the first one.
Best regards!
> Fix 'NoneType' object has no attribute 'can_read'

- AUTHORS
- kombu/transport/redis.py
- kombu/transport/virtual/base.py
- kombu/transport/virtual/exchange.py
- requirements/test.txt
- t/unit/transport/test_redis.py
> Revert "Issue #1087 redis fix"

- kombu/connection.py
- t/unit/test_connection.py
- t/unit/test_simple.py
When using SimpleBuffer from kombu.connection, exchange_opts are not filled with the parameters desired.
`queue_args` parameter was introduced in `kombu.simple.SimpleQueue` and at the same time in
`kombu.connection.SimpleQueue` method. However, `kombu.connection.SimpleBuffer`
was not updated in the same way as the other method.
As `kombu.connection.SimpleBuffer` is using positional arguments to create a
`kombu.simple.SimpleBuffer` object, the values of that instance will not have the expected values:
- `queue_args` would get the value of `exchange_opts` from kombu.connection.SimpleBuffer, because that variable is set the third one.
- `exchange_opts` would get the default value None since none was provided by the caller.
Here is the call from SimpleBuffer method and the SimpleQueue class …
> Add missing parameter queue_args in kombu.connection.SimpleBuffer

- AUTHORS
- kombu/transport/azureservicebus.py
- t/unit/transport/test_azureservicebus.py
This PR adds the possibility to setting peek lock using transport options
https://docs.microsoft.com/en-us/rest/api/servicebus/peek-lock-message-non-destructive-read
> Add peek lock settings to be possible change using transport options

- AUTHORS
- kombu/transport/redis.py
- t/unit/test_connection.py
- t/unit/transport/test_redis.py
Attempt to address https://github.com/celery/kombu/issues/1114. Added the ability to specify `health_check_interval` in `broker_transport_options`.
> Add support for health_check_interval option in broker_transport_options.

- kombu/transport/redis.py
- requirements/test.txt
- t/unit/transport/test_redis.py
resolve #1148 
I suggest adding `retry_on_timeout` as able parameter for Redis connection. 
This parameter is providing since version 2.1 of redis-py.
> Adding retry_on_timeout parameter

- kombu/utils/url.py
- t/unit/utils/test_url.py
@auvipy 
Follow up to https://github.com/celery/celery/pull/5703 in which we teach `kombu` to accept the standard `redis-py` values for the `ssl_cert_reqs` query parameter for secure `rediss://` URLs.
Tested by adding unit tests and using this version of `kombu` and `celery` 4.4.0 to connect to an AWS ElastiCache instance of Redis configured to use SSL and then launching Celery tasks successfully.
> Support standard values for ssl_cert_reqs query parameter.

- kombu/asynchronous/aws/sqs/connection.py
- kombu/transport/SQS.py
- t/unit/asynchronous/aws/sqs/test_connection.py
- t/unit/transport/test_SQS.py
Originally started in #834. I have modified the original concept of that PR. That PR added the transport setting `predefined_queue_urls`. Instead, this PR adds the transport setting `predefined_queues` so that callers can provide the SQS queue URL and the AWS credential pair. This is necessary for our current cloud environment whereby SQS queues are provisioned once outside of Kombu/Celery and we have access to the SQS queue URL and AWS creds which we need to inject into Kombu/Celery. This PR allows us to do that.
Because each queue can have its own AWS creds, I had to modify the `SQS` class `sqs` method/property so that it could be given a queue name. Given a queue name and when predefined queues are being used, a queue-specific SQS client could be returned that used the correct AWS …
> Add predefined_queues option to SQS transport

- setup.py
Use the ideas in https://python-packaging.readthedocs.io/en/latest/metadata.html to replace the __long_description__ at https://pypi.org/project/kombu with something cooler than:
`The author of this package has not provided a project description`.
Travis CI failure is fixed in #1159
> Use README.rst content as the PyPI long_description

- kombu/common.py
- t/unit/test_common.py
Raise RecoverableConnectionError in maybe_declare with retry and dropped connection
Closes #1169
> Raise RecoverableConnectionError in maybe_declare with retry 

- kombu/entity.py
Flake8 compliant this time.
Unit test to follow if possible but see no unit testing infrastructure in the repo. Fail behaviour on this is Exchange.publish(text) crashes with an encoding error.  A Pass is that the message is published, which can be confirmed with Queue.get() and comparing the payload with that which was published. Requires a running RabbitMQ instance to test (as that is the context of the crash).
A unit test though, while holding value is of the functionality of Exchange.publish() - currently broken for text messages, is not central to the value of fixing this break.
ref: https://github.com/celery/kombu/issues/1174
Apologies for a new request, inadvertently deleted the prior one (cutting my teeth with gitkraken, github and more).
> Another possible fix for #1174

- kombu/transport/sqlalchemy/__init__.py
Based on SQLAlchemy documentation:
* method `sqlalchemy.orm.query.Query.with_lockmode(mode)` with `mode='update'` - translates to `FOR UPDATE` (Deprecated since version 0.9)
* method `sqlalchemy.orm.query.Query.with_for_update()` When called with no arguments, the resulting `SELECT` statement will have a `FOR UPDATE` clause appended.
For details see:
https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.with_for_update
https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.with_lockmode
> SQLAlchemy transport: Use Query.with_for_update() instead of deprecated Query.with_lockmode().

- kombu/asynchronous/http/curl.py
- t/unit/asynchronous/http/test_curl.py
fix https://github.com/celery/celery/issues/5299
kombu uses cURL [`multi_socket`](https://curl.haxx.se/libcurl/c/libcurl-multi.html) API, which is non-blocking callback-based API. But it doesn't work well in linux, because of [epoll weird file descriptor management](https://idea.popcount.org/2017-03-20-epoll-is-fundamentally-broken-22/). When you use epoll, you must always remove FD from epoll before closing FD, but when curl decides that it doesn't need some particular socket, it will close that socket and _after that_ it will inform you that the socket is closed - so you don't have a chance to remove it from epoll in time. See https://curl.haxx.se/libcurl/c/curl_multi_socket_action.html for more info about this API.
In our case we periodically query an SQS queue, and curl performs the …
> fix 100% cpu usage on linux while using sqs

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
> Modified Mutex to use redis LuaLock implementation

- kombu/transport/sqlalchemy/__init__.py
Although a race condition in the SQLAlchmey Channel class was fixed in
a recent commit [0], a few other methods are also susceptible to race
conditions.
Indeed, if multiple threads call the class' `_open` method, a conflict
can occur with the `metadata.create_all` call which creates the schema
in the database, resulting in an exception which can look like this:
```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation)
duplicate key value violates unique constraint
"pg_type_typname_nsp_index" DETAIL: Key (typname,
typnamespace)=(queue_id_sequence, 2200) already exists.
```
Similarly, `_get_or_create` is susceptible to a race condition if two
threads try to create the unique queue object in the database at the
same time, resulting in this kind of exception:
``` …
```
> Fix: eliminate remaining race conditions from SQLAlchemy Channel

- kombu/connection.py
- t/integration/common.py
- t/integration/test_py_amqp.py
- t/unit/test_connection.py
- t/unit/transport/test_redis.py
This PR moves connection ensuring functionality into the connection factories to have consistent functionality across all API. As side efect it unifies `Connection.channel()` and `Connection.default_channel`:
1.  Now both channel factories blocks till connection is created + both provide possibility to configure this via `transport_options` parameter
2. Now both channel factories raises consistently the same exception on connection error: `kombu.exceptons.OperationalError`
Hence this change breaks backward compatibility for users which rely on this API.
Fixes #1179
> Ensure connection when connecting to broker

- kombu/connection.py
- t/unit/test_connection.py
Since #1193 `Connection.connect()` creates a new connection without saving to `Connection._connection`.
```
conn = Connection(...)
conn.connect()
conn.connected -> False
```
> set _connection in _ensure_connection

- kombu/connection.py
- t/unit/test_connection.py
#1205 recreates connection on every call to `Connection.connection` property.
```
conn.connection is not conn.connection
```
> Reuse connection

- kombu/connection.py
- t/integration/common.py
- t/unit/test_connection.py
After PR #1193 kombu does not reconnect automatically in Connection.default_channel property. This PR adds reconnect when this property is called. Fixes #1208
> default_channel should reconnect automatically

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
We have experienced some problems with the client not being able to connect to SQS and reaching the wsgi worker time limit (60s) and thus terminating. The default connect timeout for botocore is 60s and we want to be able to adjust it, so that we can handle this issue more gracefully. This PR implements a way of doing just that.
> Add an SQS transport option for custom botocore config

- .travis.yml
- tox.ini
buffer(), cmp(), and unicode() were all removed in Python 3
```
kombu/transport/qpid.py:1126:27: F821 undefined name 'buffer'
kombu/utils/encoding.py:79:26: F821 undefined name 'unicode'
kombu/utils/encoding.py:93:16: F821 undefined name 'unicode'
kombu/utils/encoding.py:95:13: F821 undefined name 'unicode'
kombu/utils/encoding.py:133:30: F821 undefined name 'unicode'
kombu/utils/encoding.py:136:20: F821 undefined name 'unicode'
kombu/utils/functional.py:239:25: F821 undefined name 'cmp'
kombu/utils/functional.py:240:20: F821 undefined name 'cmp'
t/unit/utils/test_json.py:86:22: F821 undefined name 'buffer'
```
> tox.ini: Lint on Python, not on legacy Python

- kombu/transport/qpid.py
- t/unit/transport/test_qpid.py
https://docs.python.org/2.7/library/stdtypes.html#memoryview-type
https://portingguide.readthedocs.io/en/latest/etc.html#raw-buffer-protocol-buffer-and-memoryview
> buffer() was removed in Python 3 so use bytes

- kombu/utils/encoding.py
- kombu/utils/functional.py
- t/unit/utils/test_json.py
buffer(), cmp(), and unicode() were all removed in Python 3 so mark instances with the flake8 linter directive `noqa: F821` so that it does not complain of undefined names.
> flake8: noqa the Python 2-only builtins

- kombu/utils/functional.py
Since this module has `__all__`, autodoc will (by default) only show docs for those
members, meaning retry_over_time is not shown in the rendered docs.
This function is used by the Redis result backend in Celery, and it has a doc
comment so it should be "public".
> Make `utils.functional.retry_over_time` appear in rendered docs

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
This PR contains 2 small improvements of `SentinelChannel`:
1. Sentinel connection string now supports default port 26379:
BEFORE:
```python
>>> import kombu
>>> c = kombu.Connection('sentinel://localhost', transport_options={'master_name': 'mymaster'})
>>>
>>> c.connect()
// STACKTRACE OMITTED
File "/home/environments/kombu/lib/python3.7/site-packages/redis/connection.py", line 502, in __init__
self.port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```           
AFTER
```python
>>> import kombu
>>> c = kombu.Connection('sentinel://localhost', transport_options={'master_name': 'mymaster'})
>>>
>>> c.connect()
```
2. Connection with Sentinel connection string missing `master_name` transport …
> Redis Transport: Small improvements of `SentinelChannel`

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
This reverts commit a307726faa8b64a71e04932b762498f51c1d7208.
Ref: https://github.com/celery/celery/issues/4976#issuecomment-707974799
> Revert "on worker restart - restore visible regardless to time (#905)"

- requirements/default.txt
I noticed that `vine` is directly used in a lot of places such as
https://github.com/celery/kombu/blob/10887dc88e62fe2ba51ecf09c96e7036aee93842/kombu/utils/functional.py#L13
but it's not listed as a direct dependency in the setuptools metadata.
> Add vine to install dependencies

- Changelog.rst
- Added changelog that was missing for `4.6.8`. See commits [here](https://github.com/celery/kombu/compare/4.6.7...4.6.8)
> Added 4.6.8 changelog

- kombu/asynchronous/http/base.py
There is a small typo in kombu/asynchronous/http/base.py.
Should read `property` rather than `propery`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, propery -> property

- kombu/transport/azureservicebus.py
- requirements/extras/azureservicebus.txt
- t/unit/transport/test_azureservicebus.py
Azure have completely changed the Azure ServiceBus SDK between 0.50.0 and 7.0.0. It didn't make sense to me to support the old one anymore hence the rather large refactor.
By default ASB will require you to ack messages, so have tried to incorporate that functionality. Also now for each queue the SDK gives you a sender and receiver object which behind the scenes each creates a thread, which one should not forget to close.
The PR is not finished but seems to work in some basic examples. I'm planning to clean up the implementation a bit, but would like some feedback on this as I'm not massively familiar with the Kombu codebase at the moment.
Fixes #1279
> Support for Azure Service Bus 7.0.0

- kombu/connection.py
- kombu/transport/azureservicebus.py
- kombu/transport/base.py
- t/unit/transport/test_azureservicebus.py
Firstly, it turns out `as_uri` is used by celery to generate a displayable URI with the password masked in the worker banner. ASB uri's can be incompatible with urllib.parse as they might have extra slashes because they contain base64 data. Added an optional `as_uri` method to the transport class so custom url formatting can be done if really required.
Secondly, it seems Celery sometimes does not explicitly close a Channel object, which leads to the Azure uAMQP library leaving a thread running (because its not marked as a daemon thread :/). Added some documentation about this, will raise an issue against the azure library next, though might be easier to add some logic into Celery.
Exposed some options to tune how the queue is used.
Fixed an issue when ack'ing messages when a queue isnt …
> Fix Azure Service Bus URL parsing

- kombu/asynchronous/http/curl.py
- t/unit/asynchronous/http/test_curl.py
Fixes https://github.com/celery/celery/issues/6352
CurlClient was missing the implementation for `_set_timeout`, causing a throughput limitation on Celery Worker when using SQS Broker.
---
As `add_request` calls `_set_timeout(0)` and it had no effect, requests were not starting on schedule.
https://github.com/celery/kombu/blob/ff48da68b7fd40d2d835bcc95ddd798269e92562/kombu/asynchronous/http/curl.py#L70-L74
With Curl default `max_clients=10` and the `_timeout_check` executing only once every second, it resulted in a hard limit of 10 requests per second, despite of increasing concurrency or worker_prefetch_multiplier. https://github.com/celery/kombu/blob/ff48da68b7fd40d2d835bcc95ddd798269e92562/kombu/asynchronous/http/curl.py#L55-L57
---
> celery==5.0.5
> kombu==5.0.2
Script:
```python
from …
```
> http/curl: missing _set_timeout

- kombu/utils/json.py
- t/unit/utils/test_json.py
By default, [simplejson converts namedtuple to JSON object](https://simplejson.readthedocs.io/en/latest/#simplejson.dumps) but json converts that to JSON array. 
This causes unpredictable serialization depends on installation of simplejson. So I added an option for disabling simplejson specific feature.
> Stop treating namedtuple as an object when using simplejson

- AUTHORS
- kombu/transport/redis.py
- requirements/test.txt
- t/unit/transport/test_redis.py
This brings back the naming convention refactor and the test cases to make use of the fakeredis testing module which allowed me to introduce some new tests and cleanup how imports were handled in the test file.   This was lost when my prior "redis fix" was reverted:  https://github.com/celery/kombu/pull/1106/files   
The changes here are more minimal and change not how the redis module functions, but changes it to be more readable and to update the test class to be more complete.
> Port of redis code improvements from prior revision

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
Fix the case with custom messages decoding in SQS transport
Use cases:
1) Celery with custom consumer
2) PUB/SUB with Custom publisher [SNS+SQS]
3) Non kombu/celery protocols
> fix: non kombu json message decoding in SQS transport

- .github/workflows/ci.yaml
- appveyor.yml
- requirements/test-ci.txt
- tox.ini
This PR adds 1:1 support for GH Actions CI comparing to old Travis*. PR also removes requirement for librabbitmq in CI since it is not used directly by unittests/integration tests and introduced complexity to CI + building it was timeconsuming.
* The only missing point is running unittests over pypy3 due failing unittests with complex errors (e.g. crasing in CAPI emulation layer of pypy)
﻿- Implement CI is github actions
- Skip failing pypy3 unittests
- Added integration tests
> Add Github Actions CI

- kombu/serialization.py
Protocol version 4 was added in Python 3.4 and is supported by all Python versions that kombu supports.
https://docs.python.org/3.9/library/pickle.html#data-stream-format
Fixes #1070
> Update default pickle protocol version to 4

- kombu/serialization.py
https://docs.python.org/3.9/whatsnew/3.0.html#library-changes
> A common pattern in Python 2.x is to have one version of a module implemented in pure Python, with an optional accelerated version implemented as a C extension; for example, pickle and cPickle. This places the burden of importing the accelerated version and falling back on the pure Python version on each user of these modules. In Python 3.0, the accelerated versions are considered implementation details of the pure Python versions. Users should always import the standard version, which attempts to import the accelerated version and falls back to the pure Python version. The pickle / cPickle pair received this treatment.
> Drop obsolete code importing pickle

- kombu/transport/librabbitmq.py
- kombu/transport/pyamqp.py
Using PLAIN as the default seems to have become the obvious choice:  See https://www.rabbitmq.com/authentication.html
AMQPLAIN is only retained for backwards compatability and has become non-standard.  If it's an active decision to keep AMQPLAIN I am fine with that, I've just run across many installations where people are taking AMQPLAIN out of the server config for new setups and people using kombu are wondering why their connections won't work.
> Update default login method for librabbitmq and pyamqp

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
STS token requires being refreshed after certain period of time. 
In the PR I added the functionality of creating the token and refreshing it once timeout reached   
Link to issue: https://github.com/celery/kombu/issues/1321
> SQS Broker - handle STS authentication with AWS

- kombu/transport/azureservicebus.py
- t/unit/transport/test_azureservicebus.py
In current implementation it is not possible to use dashes (`-`) in queue names. All punctuations are converted into underscores (`_`). Although the old commentary text says that dots are replaced by dashes - it wasn't working this way . 
Provided fix allows to use dashes in queue names, translates dots into dashes and translates other punctuations to underscores - just like specified in the comment above the translation table.
to test/investigate the issue you have to pass `queue_name_prefix` into `broker_transport_options` setting dict on celery.
> Azure Service Bus - versatile queue names fix

- kombu/transport/sqlalchemy/models.py
Following the changes in SQLAlchemy 1.4, the declarative base is no longer an extension.
Importing it from sqlalchemy.ext.declarative is deprecated and will be removed in SQLAlchemy 2.0.
This PR adds support for the newer versions of SQLAlchemy while maintaining backwards compatibility for previous versions.
Superceeds #1318.
> Add support for SQLAlchemy 1.4

- .github/opencollective.yml
As with the celery/celery repository, this repository is covered by our sponsership plans.
The bot is here to help us triage the issues of our sponsers and backers.
> Opencollective bot is now configured

- .github/workflows/ci.yaml
it was decided long ago and it let the unit and integrations tests run fast for faster feedback loop
> re order CI jobs to make lint the last

- kombu/asynchronous/timer.py
Celery does not coerce configuration values into the right type (See celery/celery#6696).
This is a workaround. This bug will be fixed in Celery NextGen when we will refactor our configuration subsystem.
> Coerce seconds argument to a floating point number.

- docs/conf.py
We are ignoring kombu.transport.librabbitmq because apicheck is failing
due missing librabbitmq library.
> Ignore kombu.transport.librabbitmq in apicheck.

- kombu/simple.py
- t/unit/test_simple.py
please add 'accept' parameter to SimpleQueue class
> add accept parameter to SimpleQueue class

- kombu/serialization.py
- kombu/utils/compat.py
- t/unit/test_serialization.py
When wrong serializer is passed to as accept parameter currently `KeyError` is raised. This can be misleading and confusing. Other calls uses `SerializerNotInstalled` when wrong serializer is used. This PR replaces  `KeyError` with `SerializerNotInstalled`.
After this patch all API calls providing accept parameter will raise `SerializerNotInstalled` instead of `KeyError`.
> prepare_accept_content() now raises SerializerNotInstalled instead of KeyError

- t/unit/transport/test_azureservicebus.py
Currently pytest fails to collect tests when `azure` is not present. Moving the pytest.importorskip clause before `from kombu.transport import azureservicebus` fixes it.
```
==================================== ERRORS ====================================
__________ ERROR collecting t/unit/transport/test_azureservicebus.py ___________
ImportError while importing test module '/build/python-kombu/src/kombu-5.1.0/t/unit/transport/test_azureservicebus.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
t/unit/transport/test_azureservicebus.py:12: in <module>
from kombu.transport import azureservicebus
kombu/transport/azureservicebus.py:66: …
```
>  Move pytest.importorskip to run earlier

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Although the underlying Redis package supports setting username for connections, the connection params for username are not passed to the `Redis` client.
This PR extracts the `userid` from connection info (or host) if and passes to Redis client ensuring the connection can be established for other users than the default `default` user (set when username is `None`).
**Dependencies**: None
**Testing instructions**:
1. Start Redis (using docker: `docker run --name kombu_redis --rm -it -p 6379:6379 redis:latest`)
2. Connect to redis using redis-cli in a separate terminal window (`docker exec -it kombu_redis redis-cli`)
3. List ACLs (`ACL LIST`) and validate only `default` user is listed
4. Run snippet "example 1" (defined below) and validate the message object is printed
5. Set a new password …
> Add support for setting redis username

- kombu/connection.py
- kombu/transport/pyamqp.py
- t/unit/transport/test_pyamqp.py
Add support for using hostname from URI in `server_hostname` SSL parameter when `server_hostname=None. This is usefull when URI with multiple brokers is used.
Superseeds: #744
> Use hostname from URI when server_host is None

- kombu/utils/json.py
Only use simplejson if it's absolutely necessary - Python's built-in json module is better if it's available.
> Use Python's built-in json module by default, instead of simplejson

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
Previously, calling `reject` when `predefined_queues` was not configured would cause `AttributeError` to be raised from `_extract_backoff_policy_configuration_and_message`. That exception could crash the whole Celery worker and force it to exit early because `AttributeError` is not excepted in the nearby call stack.
I work on a Red Hat project [cloudigrade](https://github.com/cloudigrade/cloudigrade/) that has been using Celery/Kombu with SQS for the last couple years, and a few days ago we saw a surprise catastrophic failure in a Celery worker that I tracked down to this problem. We had some old messages lingering in the default `celery` SQS queue for a task function that we recently removed, and normally I would expect the Celery worker to reject the message and log a warning for it, …
> SQS Channel.predefined_queues should be `{}` if not defined

- AUTHORS
- kombu/transport/redis.py
- t/unit/transport/test_redis.py
This PR continues the [work of @wetneb](https://github.com/celery/kombu/pull/912), adding a global key prefix to queue names addressing https://github.com/celery/kombu/issues/853. In the original PR, there were some unresolved issues that are resolved by this PR.
I believe most of the comments in the original approach were answered/resolved but https://github.com/celery/kombu/pull/912#pullrequestreview-166952378.
By adding the global key prefix to the `unacked_key `, `unacked_index_key`, `unacked_mutex_key` the prefix is applied for the `unacked` and `unacked_index` keys as well when the message is not ack'ed.
Also, the implementation adds the global key prefix even to the queue received by producer. Meaning that in the following example, the Redis transport will handle `a_queue_name` as …
> Add global key prefix for keys set by Redis transporter

- kombu/transport/filesystem.py
- kombu/transport/memory.py
- kombu/transport/pyro.py
- kombu/transport/virtual/base.py
- t/unit/transport/virtual/test_base.py
This PR changes BrokerState from being global to be Transport specific. This fixes issues when client is reconnecting and old BrokerState is used not matching the actual broker state. Memory and filesystem transport are still keeping global state since the implementation is not compatibile with per-transport broker state. Pyro transport is kept with global broker state for backward compatibility. Pyro transport should be retested and ported to per-transport state.
Fixes: #1377
> Make BrokerState Transport specific

- t/integration/test_redis.py
This PR runs integration tests of Redis also with global_keyprefix.
> Run integration tests for kombu also with global_keyprefix

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
> Fix: check redis response type

- kombu/pidbox.py
oid is not cached anymore due race conditions of oid in celery. Caching
oid is causing following exception:
```
OperationalError("
Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.
",)
```
This exception seems to be occuring when multiple celery workers
contains same oid.
Fixes #1063
> Prevent caching of oid in pidbox

- .github/workflows/ci.yaml
- tox.ini
`setup-python` install PyPy 3.6.12 as `pypy3`. I replaced it with `pypy-3.7` and `pypy-3.8`.
Unfortunately, Tox did not want to accept `pypy-3.7` and `pypy-3.8`, that is why I added one more step removing a hyphen from a version.
> Fix PyPy CI jobs

- kombu/transport/virtual/base.py
- t/unit/transport/test_consul.py
- t/unit/transport/virtual/test_base.py
While investigating a redis broker memory leak, I noticed the same issue as py-amqp's [#377](https://github.com/celery/py-amqp/pull/377):
```
Top 10 lines
#1: /celery_app/kombu/kombu/transport/virtual/base.py:911: 782.4 KiB
ARRAY_TYPE_H, range(self.channel_max, 0, -1),
<truncated>
```
The array that's used to store available connection ids is taking up an unnecessary amount of memory (more than anything else while running celery), and it's making memory leaks worse.
This PR reduces the memory usage of the `Transport` by reversing that logic and turning `_avail_channel_ids` into `_used_channel_ids`. This will only store the channel ids that are currently used, which is almost always going to be a much smaller array.
> reduce memory usage of Transport

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
This is related to my comment on the celery memory leak bug: https://github.com/celery/celery/issues/4843#issuecomment-999168967
I [added some logging](https://github.com/celery/kombu/compare/master...pawl:logging_insanity?expand=1#diff-203e309d100714904255d0af4500dd295e40e4ffedfdc9295ab3b386718ca87eR1333) to `on_poll_start` in the redis `Transport`'s `register_with_event_loop`, and I noticed the event loop continues to poll on redis `Transport`s that were disconnected. This causes some leftover references to the initialized `Transport` in the event loop's `on_tick` and prevents the initialized `Transport` from being garbage collected.
This is similar to the issue @michael-lazar noticed in [bug #1 in his comment about the py-amqp memory …
> prevent event loop polling on closed redis transports (and causing leak)

- kombu/connection.py
- t/unit/test_connection.py
Consider the following code which has been copied from the README file, except that I have added `transport_options={'max_retries': 3}` and `connect_timeout=1` as parameters to Connection.
```python
from kombu import Connection, Exchange, Queue
media_exchange = Exchange('media', 'direct', durable=True)
video_queue = Queue('video', exchange=media_exchange, routing_key='video')
with Connection('amqp://guest:guest@localhost//',
transport_options={'max_retries': 3},
connect_timeout=1) as conn:
producer = conn.Producer(serializer='json')
producer.publish({'name': '/tmp/lolcat1.avi', 'size': 1301013},
exchange=media_exchange, routing_key='video',
declare=[video_queue])
```
As it appears, this script should take 3 seconds to fail when rabbitmq is down, but with the current version of Kombu, it …
> respect connection timeout

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
I did some more testing with the change in #1476 and noticed that the event loop will stop polling after a "consumer: Cannot connect to redis" error from `Consumer.ensure_connected._error_handler`. This will cause celery to stop processing work. You need to stop redis for more than a few seconds to make this happen.
It can still re-connect when Redis restarts after the event loop already started, but the error above seems to happen when it's starting the `Consumer` and before `on_poll_start` runs for the first time on the new consumer.
This PR fixes the issue by checking whether event loop polling has started (based on file descriptors) and will only remove `on_poll_start` from the event loop if polling has started.
> prevent redis event loop stopping on 'consumer: Cannot connect'

- kombu/connection.py
- kombu/transport/consul.py
- kombu/transport/etcd.py
- kombu/transport/redis.py
- t/integration/test_redis.py
- t/unit/test_connection.py
- t/unit/transport/test_redis.py
I was looking into solutions for the [celery + redis memory leak issue](https://github.com/celery/celery/issues/4843#issuecomment-999168967) and I was attempting to reduce the references to initialized `Transport`s.
One thing I noticed was that you currently need at least one initialized `Transport` with an active connection to allow filling the cache for `recoverable_connection_errors`/`recoverable_channel_errors`/`connection_errors`/`channel_errors`. It seems like it makes more sense to get the errors from the `Transport` class without needing to initialize it (in case there are connection errors on the first `Transport` initialization).
This doesn't fix the memory leak issue, but maybe this change is still worth making?
> allow getting recoverable_connection_errors without an active transport 

- setup.py
This might be another potential fix for the issues in: https://github.com/celery/kombu/pull/1462
Currently we're seeing this error:
```
File "setup.py", line 60, in
scheme['data'] = scheme['purelib']
KeyError: 'purelib'
```
This seems to describe what the code with the error is doing: https://stackoverflow.com/a/3042436
That code was added in the initial commit for kombu and `data_files` is no longer defined anymore. So, maybe the hack to copy data files to the module directory isn't necessary anymore? Or maybe this should be handled in `MANIFEST.in` instead?
> prevent KeyError: 'purelib' 

- .github/workflows/ci.yaml
- requirements/pkgutils.txt
This reverts commit 6ddf9409401e290e267c9c5041d92fdf5f47170d.
Since #1467 was merged, we no longer need to pin setuptools to `<59.7.0` to avoid this error:
```
File "setup.py", line 60, in
scheme['data'] = scheme['purelib']
KeyError: 'purelib'
```
This also fixes these issues:
* https://github.com/celery/celery/discussions/7202
* https://github.com/celery/celery/pull/7194#issuecomment-1002928015
* https://github.com/celery/celery/commit/d4b97bedc79aed0b45dd3720b683d8d8572da2a9#r63108656
> Revert "try pining setuptools (#1466)"

- kombu/asynchronous/http/curl.py
- t/unit/asynchronous/http/test_curl.py
Fixes #789  
Don't reset the proxy config in the async curl based http request building unless that is specified by the caller
> Fix issue #789: Async http code not allowing for proxy config

- kombu/connection.py
The times of retrying was 'max_retries' plus 1 which is fixed now.
> The times of retrying is not correct

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Fixed setting `redelivered` value for Celery when Redis broker is used.
According to the Celery implementation, `redelivered` should be inside `delivery_info`:
- https://github.com/celery/celery/blob/25ca389039f667cdf940c9efe44bdefd1cf70f30/celery/app/trace.py#L406-L407
- https://github.com/celery/celery/blob/25ca389039f667cdf940c9efe44bdefd1cf70f30/celery/app/control.py#L358-L362
- https://github.com/celery/celery/blob/25ca389039f667cdf940c9efe44bdefd1cf70f30/celery/worker/request.py#L153-L157
It's also mentioned in the User Guide:
https://github.com/celery/celery/blob/25ca389039f667cdf940c9efe44bdefd1cf70f30/docs/userguide/tasks.rst#reject
```
from celery.exceptions import Reject
@app.task(bind=True, acks_late=True)
def requeues(self):
if not self.request.delivery_info['redelivered']: …
```
> Set redelivered property for Celery with Redis

- kombu/connection.py
- t/unit/test_connection.py
The `No hostname was supplied` warning is affecting projects that use AWS SQS (as detailed in #1357), as a hostname is not required when setting up the broker URL. Instead, the official documentation [0] specifies that the valid broker URL formats are:
* `sqs://`
* `sqs://aws_access_key_id:aws_secret_access_key@`
With these formats, the `kombu.utils.url.parse_url` util doesn't return a hostname, and workers end up triggering the following warning:
> No hostname was supplied. Reverting to default 'None'
As the SQS transport doesn't provide a default value for hostname, this diff changes the behavior to only warn the user when the hostname hasn't been supplied but a default one is being set by the default connection parameters for the defined transport.
Fixes #1357.
[0] …
> Warn about missing hostname only when default one is available

- kombu/__init__.py
https://www.python.org/dev/peps/pep-0366/ lists Python 2.6 and 3.0 as
the minimum requirements for this attribute. `sys.__dict__` contains it.
@thedrow @auvipy Can you please double check this?
> All supported versions of Python define __package__.

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Fixes #1494 
Need help with testcases.
> Added global_keyprefix support for pubsub clients

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
I would like to suggest this enhancement. It adds an option to disable the base64 encoding of all message bodies in SQS. Since the messages are already JSON encoded, there is no need to also encode them in base64; SQS allows all characters produced by the Python JSON library.
This patch also simplifies the base64 decoding logic so that we don't have to run base64 decoding twice for every message that's encoded in base64.
> Add an option to not base64-encode SQS messages.

- kombu/transport/SQS.py
Hi!
I just found an error in SQS implementation regarding backoff tasks. There was already notion of this [here](https://github.com/celery/kombu/pull/1372) or [here](https://github.com/celery/kombu/issues/1358). I still experience this problem when backoff policy is defined explicitly. [Prepared small example to reproduce issue](https://gitlab.com/amonowy/celery-sqs-reproduce). Fix is in this PR.
I'm open to comments and happy to improve this PR!
Error is here:
[err.txt](https://github.com/celery/kombu/files/8142965/err.txt)
> SQS: Fix message arg in backoff policy

- kombu/transport/filesystem.py
- t/unit/transport/test_filesystem.py
Looks like #1280 is stale? 
filesystem transport lacks of fanout support.
1. Add fanout support to filesystem transport.
2. Add a unit test for it.
> Add fanout to filesystem

- kombu/asynchronous/hub.py
- t/unit/asynchronous/test_hub.py
When there is no locking then there is a possibility that multiple threads manipulate with the same object at the same time.
The issue is manifested when the celery worker is run in the threading model and fails with the following exception:
```
RuntimeError: Set changed size during iteration
```
I don't think we can create reliable tests for this change.
See: https://github.com/celery/celery/issues/7162
> Protect set of ready tasks by lock to avoid concurrent updates

- docs/userguide/serialization.rst
According to the [changelog](https://docs.celeryq.dev/projects/kombu/en/latest/changelog.html#b1) kombu now uses pickle protocol version 4 by default
> Documentation: Update serialization page to indicate pickle protocol version has been updated

- kombu/utils/json.py
- requirements/test.txt
- t/unit/utils/test_json.py
Signature args in callback_msg should be serializable, so
```
callback_msg = str(uuid.uuid4()).encode()
redis_key = str(uuid.uuid4())
callback = redis_echo.si(callback_msg, redis_key=redis_key)
```
,so should be
as they will be passed inside as_task_v2 that would return message that would be passed to a send_task_message, then to publish (kombu) and _prepare (kombu) in messaging that would cll a serialization (kombu).
```
from kombu.serialization import dumps
s = ((42,), {}, {'callbacks': [{'task': 't.integration.tasks.redis_echo', 'args': (b'7a108737-0b0a-4acc-a32f-f8a5e6726775',), 'kwargs': {'redis_key': 'ef3bc79f-a04c-4de1-88c0-f13d9d999ca8'}, 'options': {}, 'subtask_type': None, 'immutable': True}], 'errbacks': None, 'chain': None, 'chord': None})
print(dumps(s))
```
to reproduce …
> Added possibility to serialize and deserialize binary messages in json

- kombu/utils/text.py
- kombu/utils/uuid.py
- setup.cfg
- t/unit/utils/test_uuid.py
> Annotate `utils/uuid.py` and `utils/text.py`

- kombu/asynchronous/http/base.py
- kombu/asynchronous/timer.py
- kombu/compat.py
- kombu/connection.py
- kombu/messaging.py
- kombu/resource.py
- kombu/simple.py
- kombu/transport/base.py
- kombu/transport/virtual/base.py
- t/mocks.py
- t/unit/asynchronous/test_semaphore.py
- t/unit/test_common.py
- t/unit/test_compat.py
- t/unit/test_connection.py
- t/unit/test_messaging.py
- t/unit/test_simple.py
- t/unit/transport/test_redis.py
- t/unit/transport/virtual/test_base.py
Follow up from #1513
Relates to #1511
PR updates all `__exit__` function signatures, and adjusts (now) failing tests that were calling `__exit__` without any arguments (which I seems incorrect)
> Update `__exit__` function signatures

- docs/reference/kombu.serialization.rst
- docs/userguide/serialization.rst
- kombu/utils/json.py
We import `import json as stdjson`, but then we try again to `import json` and otherwise do `import simplejson`. This is the legacy of Python 2.7 and there is no need to support that.
Issue: #1528
> json.py cleaning from outdated libs

- kombu/transport/redis.py
Although HLEN is not used anywhere inside kombu or celery, it is the method that is used to get the count of unacked messages.
This can be used similar to monitoring celery queue length.
The unacked_key that is used to store info about the unacknowledged tasks is a hash.
If I wish to identify whether all celery tasks have been processed, I need to ensure that the unacked_key is empty along with queues length also.
When using a prefix, HLEN should also use the same key prefix.
> Added HLEN to the list of prefixed redis commands

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
The [Redis WATCH command](https://redis.io/commands/watch/) accepts multiple keys as arguments -- all of those keys should be prefixed using the `global_keyprefix` setting.
Kombu does not execute this command directly, but the command is used when running Redis transactions (restore tag and restore message).
Fixes #1569
> Add Redis WATCH to prefixed complex commands

- docs/userguide/serialization.rst
- kombu/utils/json.py
- t/unit/utils/test_json.py
Serializing UUIDs as strs and deserializing them as strs can lead to
somewhat obscure bugs such as the one that led to the creation of this
PR in django-cacheback
https://github.com/codeinthehole/django-cacheback/pull/100 which some
would call unexpected behaviour.
After all, an UUID is altogether a different type from strs and if
bytes got their own serializer/deserializer for UUID the same logic
should apply.
I added a case for every uuidX constructor found in CPython.
Lemme know what you think of it and if there's anything I'm misreading :D.
P.D: I understand that UUIDs are now serialized as a convenience for users
but perhaps it's a bit non-intuitive that after versions of not supporting them
now they're converted to a different type when deserializing?
> Avoid losing type of UUID when serializing/deserializing

- kombu/transport/azurestoragequeues.py
Saves `QueueProperties` objects (rather than `QueueClient` objects) into the `_queue_name_cache` dictionary. 
Fixes a bug where calling `QueueServiceClient.get_queue_client` with a `QueueClient` object resulted in type errors further down the line.
Fixes #1585 
Related to #1539, #1468 and possibly #1168
> Fix azurestoragequeues transport

- kombu/transport/filesystem.py
- t/unit/transport/test_filesystem.py
fix: #398
Currently only write lock used in msg/exchange file written. Cause
reading in other thread got some incomplete result.
1. Add timeout for the lock acquire.
2. Add Share locks when reading message from filesystem.
3. Add a unit test for the `lock` and `unlock`
4. Add a unit test to test the lock during message processing.
> Solve Kombu filesystem transport not thread safe

- kombu/transport/filesystem.py
- t/unit/transport/test_filesystem.py
Reverts celery/kombu#1593 
Sorry, the PR created by me works even worse than previous on our program. It only solved part of the problem and introduce a new one. I'll create a new PR later. 
The previous problem comes from: 
1. in `_queue_bind`
```python
def _queue_bind(self, exchange, routing_key, pattern, queue):
queues = self.get_table(exchange)
queue_val = exchange_queue_t(routing_key or "", pattern or "",
queue or "")
if queue_val not in queues:
queues.insert(0, queue_val)
with self._get_exchange_file_obj(exchange, "wb") as f_obj:
f_obj.write(str_to_bytes(dumps(queues)))
```
We first read the table and then add a new line to it. We do add a lock during both progress but released it too quickly and the file might change between these two progress. 
2. in `_get` and `_purge` we …
> Revert "Solve Kombu filesystem transport not thread safe"

- AUTHORS
- kombu/utils/json.py
- t/unit/utils/test_json.py
Otherwise Celery jobs start to get `datetime` in place of `date` and that could lead to errors.
See https://github.com/celery/celery/issues/7754, related PR #1515.
> Make JSONEncoder keep the same type for date/datetime.

- kombu/utils/compat.py
- requirements/default.txt
Closes https://github.com/celery/kombu/issues/1600
See https://github.com/python/importlib_metadata/pull/405
> importlib_metadata remove deprecated entry point interfaces

- kombu/__init__.py
- t/unit/test_pools.py
- t/unit/transport/test_memory.py
- t/unit/transport/test_pyro.py
- t/unit/transport/virtual/test_base.py
Python's `del` is a statement, not a function, and doesn't need parenthesis.
The flake8 lint has been failing in kombu for a while now, this fixes the failures.
> Fix errors from flake8 lint

- kombu/transport/azurestoragequeues.py
- t/unit/transport/test_azurestoragequeues.py
When integration testing the `azurestoragequeues` transport locally using [Azurite](https://github.com/Azure/Azurite) within a docker-compose stack, the queue url becomes `http://<service>:10001/devstoreaccount1` rather than `http://localhost:10001/devstoreaccount1` where `<service>` is the name of the azurite service in docker-compose. As described in [this issue on the Azure python SDK](https://github.com/Azure/azure-sdk-for-python/issues/19202), this results in a failure to connect to the queue service. This PR applies the suggested workaround in [this comment](https://github.com/Azure/azure-sdk-for-python/issues/19202#issuecomment-1158057765) to enable the kombu transport to work with Azurite in local docker-compose stacks for integration testing.
This PR should close #1168
> Allow azurestoragequeues transport to be used with Azurite emulator in docker-compose

- kombu/connection.py
- t/unit/test_connection.py
To be used with [task_publish_retry_policy](https://github.com/celery/celery/blob/7b585138af8318d62b8fe7086df7e85d110ac786/celery/app/defaults.py#L270)
> Allowing `Connection.ensure()` to retry on specific exceptions given by policy

- .pre-commit-config.yaml
- kombu/utils/text.py
I observed a lot of ci failures related to unused typing imports being reported by flake8. This change makes it so that these will automatically get cleaned up by the pre-commit.ci bot.
> add autoflake to .pre-commit-config.yaml to automatically remove unused imports

- .github/workflows/codeql-analysis.yml
- README.rst
- docs/templates/readme.txt
- requirements/dev.txt
This PR changes the remains of the references to master that we didn't change yet to main.
I also noticed our build status still refers to Travis which is now not in use anymore so we now use the correct badge from Github Actions.
> Switch references to the master branch to main

- .pre-commit-config.yaml
Per https://github.com/celery/kombu/pull/1632 @thedrow asked to add this argument so `Optional` is still used.
> add --keep-runtime-typing argument to pyupgrade

- kombu/transport/azurestoragequeues.py
This isn't complete, but at least it's a start. I'm open to any feedback.
> add type annotations to kombu/transport/azurestoragequeues

- kombu/transport/azureservicebus.py
- t/unit/transport/test_azureservicebus.py
Title is self explanatory.
I converted some instance methods from `@property` to `@cached_property` because it's less verbose and I assumed that was the actual intent.
There is one underlying change too which I can't tell if it was a bug or by design, I'd like someone else to review to make sure I'm not changing the intended behavior.
> azure service bus: add type annotations and use cached property

- kombu/abstract.py
In MaybeChannelBound, the `__call__()`, `bind()` and `maybe_bind()` methods takes a channel argument. The type annotation say this argument must be a Channel, but it goes through `maybe_channel()`, so it can also be a Connection. Update the annotation to accept both Channel and Connection.
> Mark methods accepting Connection instances as such

- kombu/serialization.py
Looks like `_setupfuns` is unused and should be removed.
If they're used somehow, please explain how, so i can add comment here to avoid future confusion.
> Remove unused `_setupfuns` from serialization.py

- t/unit/utils/test_compat.py
> Correctly mock entry_points on Python 3.10

- kombu/transport/mongodb.py
- t/unit/transport/test_mongodb.py
- replace obsolete collection `remove` by `delete_one`
- add test mock `spec` to check valid methods corresponding to the real objects
(`AttributeError` raised if real class does not have this attribute/method)
Validated with latest celery using `celery inspect` calls that were failing before this fix.
- fixes #1689
> fix mongodb transport obsolete calls

- kombu/transport/SQS.py
- kombu/transport/virtual/base.py
- t/unit/transport/test_SQS.py
The first commit fixes #1618.
The second clarifies some comments & variable names which I found confusing while trying to figure out what was going on.
> SQS: avoid excessive GetQueueURL calls by using cached queue url

- requirements/extras/azureservicebus.txt
Update to the newest service bus library that is built on pure python AMQP stack.   `uamqp` is no longer a requirement and will help yall with the pypy CI
> Update to Latest Service Bus Library

- .github/workflows/ci.yaml
Improvements found while I was working on https://github.com/celery/kombu/pull/1705.
- Use exact tag for `setup-python` GH action.
- Get rid of dash stripping step for PyPy 3.9 version as [setup-python GH action supports using `pypy3.9` reference](https://github.com/actions/setup-python#basic-usage).
`ci.yaml` GitHub Actions workflow has been run locally using [`act`](https://github.com/nektos/act), with the following command:
```
act -W .github/workflows/ci.yaml
```
> chore(ci): improve CI

- setup.py
Cleaning before https://github.com/celery/kombu/pull/1705.
This PR:
- removes `zip_safe` parameter as this is considered deprecated and used for egg distribution format, cf. https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html.
- removes `cmdclass` as it seems unused, cf. https://setuptools.pypa.io/en/latest/userguide/extension.html for more context.
> chore(build): clean `setup.py`

- .github/workflows/ci.yaml
- kombu/utils/compat.py
- requirements/default.txt
- setup.py
- tox.ini
Improvement found while I was working on https://github.com/celery/kombu/pull/1705.
As Python 3.7 will reach end-of-life in June 2023, we can get rid of Python 3.7 support. 
Python 3.8.1 instead of 3.8.0 is required as a requirement for `flake8>=6.0.0`, cf. https://github.com/celery/kombu/pull/1709.
> chore(python): remove Python 3.7 support

- requirements/default.txt
- requirements/test.txt
> add missing zoneinfo dependency

- requirements/default.txt
https://github.com/celery/kombu/issues/1731#issuecomment-1571887264
`ZoneInfo("UTC")` works on linux without the extra `tzdata` dependency. It doesn't work on Windows without `tzdata`. It doesn't work for any other time zones like `CET` on any OS.
So I propose to always install `tzdata`.
> zoneinfo: the actual timezone data is an optional dependency

- kombu/utils/json.py
- t/unit/utils/test_json.py
In PR #1575 a new serializer for UUIDs was introduced, however it fails when deserializing UUIDs which version is not within 1 and 5. Given that there's a new standard (https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-04) gaining traction that introduces UUIDs v6, v7 and v8, we change the code to allow such versions.
In the test, we generate one UUID for each version using the package `uuid6` (https://github.com/oittaa/uuid6-python)
Fixes #1750 1750
> fix: allow deserializing any version of UUID

- kombu/connection.py
- t/unit/test_connection.py
#1629 introduced a constraint forcing setting `max_retries` when it was originally designed to be able to be `None` for infinite retries.
This PR relaxes back the constraint as it was before while keeping the change from #1629
> Reverted unwanted constraint introduced in #1629 with max_retries

- kombu/utils/objects.py
Consider the following piece of code, very similar to what can be found
in kombu/utils/objects.py:
---8<------------------------------------------------------------------
$ cat  /tmp/x.py
try:
from functools import _NOT_FOUND
from functools import cached_property as _cached_property
except ImportError:
from cached_property import threaded_cached_property as _cached_property
_NOT_FOUND = object()
print("OK!")
---8<------------------------------------------------------------------
This works well in Python3.11:
---8<------------------------------------------------------------------
$ podman run -it --rm -v /tmp:/tmp python:3.11.4  python /tmp/x.py
OK!
---8<------------------------------------------------------------------
But fails in Python3.12: …
> Python3.12: fix imports in kombu/utils/objects.py

- docs/userguide/simple.rst
It seems SimpleQueue is not used in the example below.
> docs: Remove SimpleQueue import

- kombu/transport/azureservicebus.py
This is a work in progress. I still need to add a bunch of unit tests.
edit 1: I spent a bunch of time trying to get the unit tests to work and failed in my efforts. I have been running this code in production since this PR was originally opened (Feb 2023).
> azure service bus: add managed identity support

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
The redis poller uses the [BRPOP](https://redis.io/commands/brpop/) command to pull items from the queue:
> BRPOP is a blocking list pop primitive. It is the blocking version of [RPOP](https://redis.io/commands/rpop) because it blocks the connection when there are no elements to pop from any of the given lists. An element is popped from the tail of the first list that is non-empty, with the given keys being checked in the order that they are given.
If the channel is closed before the `BRPOP` [response is read](https://github.com/celery/kombu/blob/e5299379b002b0b663562d073735bf9f05c62333/kombu/transport/redis.py#L956), there is a risk that a task will be popped from the queue, but never picked up or restored:
```mermaid
sequenceDiagram
Worker->>Redis: Worker issues BRPOP command to redis, …
```
> fix: Prevent redis task loss when closing connection while in poll

- docs/userguide/connections.rst
+ celery with sqs #222
SQS broker url doesn't include queue_name_prefix #222
ANSWER:-
I have used the below code for queue_name_prefix...
It is in Flask App running on production..
from celery import Celery
def make_celery(app):
celery = Celery(
app.import_name,
broker="sqs://",
broker_transport_options={
"queue_name_prefix": "{SERVICE_ENV}-{SERVICE_NAME}-"
},
)
task_base = celery.Task
class ContextTask(task_base):
abstract = True
def __call__(self, *args, **kwargs):
with app.app_context():
return task_base.__call__(self, *args, **kwargs)
celery.Task = ContextTask
return celery
> Kombu & celery with SQS #222

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
This change enhances the error handling within the system by specifically addressing the situation where access to an AWS queue is denied.
fixes: https://github.com/celery/kombu/issues/1768
> Handle Access Denied Exception in basic_ack Method

- kombu/transport/azureservicebus.py
- t/unit/transport/test_azureservicebus.py
When using managed identities with azure service bus the connection fails as mentioned in #1345 
This PR is a continuation of #1641
> fix azure servicebus using managed identity support

- kombu/asynchronous/aws/sqs/connection.py
- kombu/asynchronous/aws/sqs/queue.py
- kombu/transport/SQS.py
- t/unit/asynchronous/aws/sqs/test_connection.py
- t/unit/asynchronous/aws/sqs/test_queue.py
- t/unit/transport/test_SQS.py
> Revert "[fix #1726] Use boto3 for SQS async requests"

- kombu/utils/objects.py
- t/unit/utils/test_objects.py
This fixes #1804 (fixing breakage caused by use of undocumented implementation details of functools.cached_property) by ensuring a lock is always present on cached_property attributes, which is required to safely support setting and deleting cached values in addition to computing them on demand.
> Create a lock on cached_property if not present

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
this bug is ack concurrency caused by del unack key.
for debug i print full stack :
delete a58b8b31-c8c8-4c1e-88d9-f857bbf375a2 unacked_index
File "/home/jiangxf/py3/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
return callback(message)
File "/home/jiangxf/py3/lib/python3.10/site-packages/kombu/messaging.py", line 656, in _receive_callback
return on_m(message) if on_m else self.receive(decoded, message)
File "/home/jiangxf/py3/lib/python3.10/site-packages/kombu/messaging.py", line 622, in receive
[callback(body, message) for callback in callbacks]
File "/home/jiangxf/py3/lib/python3.10/site-packages/kombu/messaging.py", line 622, in <listcomp>
[callback(body, message) for callback in callbacks]
File "/home/jiangxf/test_kombu.py", line 22, in …
> fix: redis requeue concurrency bug  #1800

- kombu/transport/confluentkafka.py
- requirements/extras/confluentkafka.txt
- tox.ini
class NoBrokersAvailable(confluent_kafka.KafkaException):
E   AttributeError: 'NoneType' object has no attribute 'KafkaException'
kombu/transport/confluentkafka.py:89: AttributeError
=============================== warnings summary ===============================
t/integration/test_kafka.py:46
> Bump kafka deps versions & fix integration test failures

- kombu/asynchronous/aws/connection.py
- kombu/asynchronous/aws/sqs/connection.py
- t/unit/asynchronous/aws/sqs/test_connection.py
TL;DR - The use of boto3 in #1759 resulted in relying on blocking (synchronous) HTTP requests, which caused the performance issue reported in #1783.
`kombu` previously used to craft AWS requests manually as explained in detail in #1726, which resulted in an outage when botocore temporarily changed the default protocol to JSON (before rolling back due to the impact on celery and airflow.) To fix the issue, I submitted #1759, which changes `kombu` to use `boto3` instead of manually crafting AWS requests. This way when boto3 changes the default protocol, kombu won't be impacted.
While working on #1759, I did extensive debugging to understand the multi-threading nature of kombu. What I discovered is that there isn't an actual multi-threading in the true sense of the word, but an event loop …
> Use the correct protocol for SQS requests

- kombu/connection.py
Hey,
* Ran into this when trying to setup `celery` configuration to correctly support SSL using a Redis backend. It *is* supported but this bit of documentation had me second guessing things
* As-per [my comment](https://github.com/celery/kombu/issues/1493#issuecomment-1829589295) on #1493 with a working configuration, this is working as expected in the current release
> fix(docs): add Redis to the list of transports where SSL is supported

- kombu/utils/div.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [div.py](https://github.com/celery/kombu/blob/main/kombu/utils/div.py#L19), there is a method that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the [Python documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). iCR suggested that a temporary file should be created using `mkstemp` which is a [safe API](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp). iCR replaced the usage of mktemp with `mkstemp`.
- [POC - Improper Method Call - python - mktemp.mp4](https://drive.google.com/file/d/16YKuKgv7iItWcac2biRyi2Cm8upJ3HP_/view?usp=share_link)
- [MISC - Python - Taking a peek under the tempfile …
> Fixed Improper Method Call: Replaced `mktemp`

- kombu/asynchronous/hub.py
- kombu/transport/redis.py
- t/unit/asynchronous/test_hub.py
Relates to https://github.com/celery/kombu/issues/1774
With redis broker, when the redis server reaches timeout and celery worker is running a long cpu-intensive task, the transport tick automatically disconnects, and that's expected.
The connection error is thrown by the `redis-py` lib, but before that happens, the redis transport layer is auto-disconnected.
Instead of propagating the `ConnectionError`, the async hub gets its ticks set changed in the middle of the for loop that executes its callbacks, resulting in an error such as `RuntimeError: Set changed size during iteration`.
This happens because one of these callbacks belongs to the transport layer itself.
This solution basically freezes those ticks sets so they keep their consistency until the `ConnectionError` is thrown, which …
> fix: freeze set during ticks iter in async hub

- kombu/transport/azureservicebus.py
- t/unit/transport/test_azureservicebus.py
When trying the new version of Kombu I get the following error:
```
TypeError("argument of type 'DefaultAzureCredential' is not iterable")
File "/usr/local/lib/python3.8/dist-packages/celery/worker/worker.py", line 202, in start
self.blueprint.start(self)
File "/usr/local/lib/python3.8/dist-packages/celery/bootsteps.py", line 112, in start
self.on_start()
File "/usr/local/lib/python3.8/dist-packages/celery/apps/worker.py", line 135, in on_start
self.emit_banner()
File "/usr/local/lib/python3.8/dist-packages/celery/apps/worker.py", line 169, in emit_banner
' \n', self.startup_info(artlines=not use_image))),
File "/usr/local/lib/python3.8/dist-packages/celery/apps/worker.py", line 230, in startup_info
conninfo=self.app.connection().as_uri(),
File …
```
> azure service bus: fix TypeError when using Managed Identities

- kombu/transport/virtual/base.py
There is typo in the spelling of `unacknowledged` in the `restore_visible` function. It is fixed in this PR.
> Fix unacknowledge typo in restore_visible()

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
Fix for https://github.com/celery/kombu/issues/1809.
When global_keyprefix is set, self.Client is no longer a class, it is a closure to create the class with the prefix argument.  This breaks in a place that expects this to be a class and not just any callable.  Fortunately, in this particular case, the place that is breaking doesn't actually need or care about the prefix and so it is safe to use the main redis client class.  It only cares about the pool that comes back.  This fix does not prevent the key prefix from being used later by kombu's own client extension.
> Fix crash when using global_keyprefix with a sentinel connection

- kombu/entity.py
- t/unit/test_entity.py
- t/unit/transport/test_pyamqp.py
When broker send Basic.cancel notification, py-amqp default behavior is to raise a ConsumerCancelled exception. It is then treated as an error even if connection and channel are still operationnal and connection is closed.
Basic.cancel may be sent by broker when a queue is deleted or when replicated queue leader change. py-amqp channel.basic_consume allow to define a callback function on this event. It may be useful to register this callback from kombu when consuming from a queue.
> Expose cancel callback from py-amqp channel.basic_consume

- kombu/transport/redis.py
- t/unit/transport/test_redis.py
I've created an issue for this PR: https://github.com/celery/kombu/issues/1987
> fix: Fanout exchange messages mixed across virtual databases in Redis sentinel

- requirements/test-ci.txt
- t/unit/transport/test_etcd.py
Enabled and fixed test_etcd.py. See [Issue 2001](https://github.com/celery/kombu/issues/2001).
Added etcd requirements and fixed the test in line with test_consul.py
> enable/fix test_etcd.py (resolves #2001)

- requirements/default.txt
- tox.ini
Extracted from https://github.com/celery/kombu/pull/2007 by @awmackowiak
Due to: https://github.com/docker/docker-py/issues/3256
> Limit requests<2.32.0 due to docker-py issue 3256

- kombu/mixins.py
broker heartbeats clutter the logs console which prevents users from seeing important logs. this allows users to disable broker heartbeats if timeout isn't provided.
[reference issue](https://github.com/celery/kombu/issues/1997)
> enhance: allow users to disable broker heartbeats 

- kombu/mixins.py
- t/unit/test_mixins.py
Hi,
I took the liberty to add a test case for #1998. I was not able to add to that request so created (upon advise) a new PR with the change in it as well. The original change was done by @smart-programmer and resolves #1997. Hopefully this is enough to close the issues (this, #1997 and #1998).
I basically verified if the heartbeat_check is called/not called based upon the timeout value.
> enhance: allow uses to disable broker heartbeats by not providing a timeout (#1997,#1998)

- kombu/log.py
- kombu/utils/debug.py
- setup.cfg
This PR adds annotations to `utils/debug.py` and adds the file to `mypy` whitelist.
> chore(typing): annotate `utils/debug.py`

- kombu/connection.py
- kombu/resource.py
- t/unit/test_connection.py
Hi, can you please have a look at this pull request. It addresses the issue #2018.
What did I do to tackle the issue. First I added several test case for the resize method (in test_connection.py), as they were not available. Basically the test test_acquire_resize_reset() triggered the given issue.
In short the use of force_close_all() (used also in other cases) caused the pool to be set on _closed = True. In the acquire method this resulted in the RuntimeError('Acquire on closed pool'). 
I've added a parameter **close_pool** in force_close_all with default of True (old behaviour as used by other callers), which allows the pool to be kept open if set to False. In the resize method, reset branch I've added force_close_all(close_pool=False).
PLEASE NOTE:
While testing the resize I've found 2 …
> ConnectionPool can't be used after .resize(..., reset=True) (resolves #2018)

- kombu/connection.py
- kombu/transport/redis.py
- t/unit/transport/test_redis.py
**TL;DR**
After updating to version 5.2.3, Celery workers stop processing tasks indefinitely after losing connection to the Redis broker.
This issue does not occur in version 5.2.2. Analysis revealed that the problem is related to the removal of new Redis connections from the `on_tick` method and the behaviour of the `__del__` method, which removes these connections before they are properly registered.
The solution is to modify the logic for removing connections from on_tick so that only connections that were properly added to the poller are removed, thereby resolving the reconnection issue.
This cannot be made without @ziollek because he figure out the GC problem and proposed a simple solution.
Big thanks to him :)
**Full Description**
_Problem_
After losing connection to the Redis …
> Fix Redis connections after reconnect - consumer starts consuming the tasks after crash.

- kombu/transport/mongodb.py
If we try run kombu with scheme `mongodb+srv`, it will break during URL parsing.
Fixes: #1786
Fixes: #858
> Add support for mongodb+srv scheme

- .github/workflows/ci.yaml
For some reason, unit tests for python 3.9 are hanging when running via GitHub Actions.
Locally, it passes successfully:
```
3.8-unit: OK (63.03=setup[21.26]+cmd[41.77] seconds)
3.9-unit: OK (61.05=setup[20.77]+cmd[40.28] seconds)
3.10-unit: OK (61.68=setup[20.60]+cmd[41.08] seconds)
3.11-unit: OK (62.84=setup[20.64]+cmd[42.20] seconds)
3.12-unit: OK (62.81=setup[22.25]+cmd[40.56] seconds)
```
There wasn’t any PR that made changes that should break `3.9-unit` tests but at this moment this is blocking from the rest of the CI to run and from validating further changes.
This is not ideal and should be reverted as soon as possible, but for now I want to skip 3.9 to allow the rest of the CI to run.
It is less probable that something that passes `3.8-unit` will not also pass `3.9-unit` in case …
> Exclude Unit 3.9 from CI

- .github/workflows/ci.yaml
This should be have been caught during the work on #2046 
In another PR it is worth upgrading the CI yaml, *sigh*...
> Fixed CI error from excluding Python 3.9 unit tests

- kombu/transport/virtual/base.py
when a message has an `properties`.`body_encoding` of `utf-8` (e.g. the default on https://github.com/node-celery-ts/node-celery-ts), celery workers crash with an error `AttributeError: 'NoneType' object has no attribute 'decode'`. `utf-8` is functionally equivalent to not providing an encoding, so this should be good.
> fix: don't crash on `properties`.`body_encoding`: `utf-8`

- kombu/transport/azureservicebus.py
> fix azure service bus isinstance checks when None

- kombu/transport/redis.py
Usage of `logging.Logger.warn` was deprecated since Python 3.3 and it will be removed in Python 3.13: https://docs.python.org/3.13/whatsnew/3.13.html#logging
There is a pull request (https://github.com/celery/kombu/pull/2052) with similar changes, however merging that PR will likely take time. At the same time, Fedora 41 comes with Python 3.13 and packages kombu. A similar patch can be found in https://src.fedoraproject.org/rpms/python-kombu/pull-request/10. To avoid the need for distro-specific patches (see https://pkgs.org/search/?q=python3.13 for distros that come with Python 3.13), I propose to make this change in this upstream repository.
Unfortunately, I could not find an easy way to prevent issues like this with linters: the current stable version of `mypy` does not find this issue …
> Use logging.Logger.warning

- Changelog.rst
- docs/reference/kombu.transport.SQS.rst
- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
Hi!
I looked for a contributing guide and couldn't find one, so apologies if I missed any requirement/need.
SQS supports MessageAttributes, and with this PR, users using celery can easily add message attributes like this:
```python
from celery import Celery, signature
app = Celery('sqs_producer', broker='sqs://')
app.conf.update(
broker_transport_options={
'region': 'eu-north-1',
'polling_interval': 1,
},
task_default_queue='ManualTesting1'
)
def custom_signature(message_body):
return signature('sqs_producer.send_message_to_sqs', args=(message_body,))
if __name__ == '__main__':
message_body = {
'key1': 'value1',
'key2': 'value2'
}
task = custom_signature(message_body)
result = task.apply_async(message_attributes = {
'Attribute1': {'DataType': 'String',
'StringValue': 'STRING_VALUE'}
}) …
```
> SQS: add support for passing MessageAttributes

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
Fix for issue [#2091](https://github.com/celery/kombu/issues/2091)
`.queue_delete()` method of SQS channel is not actually deleting the queue. See implementation [here](https://github.com/celery/kombu/blob/1dddf9949fd763da03128bfa0c96fa92446c0146/kombu/transport/SQS.py#L413).
```
def _delete(self, queue, *args, **kwargs):
"""Delete queue by name."""
if self.predefined_queues:
return
super()._delete(queue)
self._queue_cache.pop(queue, None)
```
* I managed to call `delete_queue` using sqs client (`boto3`).
* I wrapped logic to resolve queue URL into a reusable method `_resolve_queue_url` method for reusability.
* I added unit tests coverage for new changes.
I took the liberty of creating a new method (`_resolve_queue_url`). I found it convenient to delegate the responsibility of resolving …
> SQS: Fixes #2091 queue_delete() method doesn't actually delete the queue

- kombu/utils/text.py
- t/unit/utils/test_utils.py
This will make sure that the version unpacking doesn't stop connection to some versions of message brokers. For message brokers with normal-style version, say 3.13.6, 
```Pyhon
def version_string_as_tuple(s: str) -> version_info_t:
"""Convert version string to version info tuple."""
v = _unpack_version(*s.split('.'))
...
```
will result in `['3', '13', '6']` list. But for newer releases of rabbitmq, say when you pull docker image using a specified version, in my case `4.0-rc` as discussed in this  [issue](https://github.com/celery/celery/issues/9161#issuecomment-2288083848) related to #2088 it becomes this:
```Python
['4', '0', '0+beta', '2', '6', 'g65c3daf']
```
which causes that `TypeError`.
> Resolving TypeError, during version unpacking 

- kombu/mixins.py
- t/unit/test_mixins.py
Hello,
In issue #2097 it is mentioned that #1997, #1998, #2016 caused heartbeats not to be sent any more if timeout is None or 0. I'm not sure if we want to revert the change from @smart-programmer but this pull request will do so. Perhaps @auvipy can give his opinion. I reverted the change and changed the test case to expect the opposite old behavior which is to send heartbeats even if timeout is None or 0.
Please review and decide if revert is wanted or not.
With kind regards,
Frank
> Revert: allow users to disable broker heartbeats by not providing a timeout (#2097, #2016)

- kombu/asynchronous/aws/connection.py
Reverts celery/kombu#2094 per the conversation in https://github.com/celery/kombu/issues/2113
> Revert "Validate SQS SSL certs by default"

- t/unit/transport/test_filesystem.py
`fcntl` is not working on Windows (as well as concurrent file opening)
if i'm not mistaken ;) 
this PR skips failing test on Windows
> fix(pytest): skip file-lock test on Windows

- kombu/connection.py
- t/unit/test_connection.py
Before this change, retry over time did not call the errback or callback if specified in `broker_transport_options`.
This PR fixes this bug by including them in connection options.
> Apply errback and callback when retry occurs

- docs/reference/kombu.transport.gcpubsub.rst
- kombu/transport/__init__.py
- kombu/transport/gcpubsub.py
- requirements/extras/gcpubsub.txt
- requirements/test-ci.txt
- setup.py
- t/unit/transport/test_gcpubsub.py
- tox.ini
Add support for GCP Pub/Sub 
* Add tests
* Add docs
Fix: https://github.com/celery/kombu/issues/705
Fix: https://github.com/celery/celery/issues/3984
> Add support for Google Pub/Sub as transport broker

- kombu/messaging.py
- t/unit/test_messaging.py
In https://github.com/celery/kombu/blob/2f5882331237147ccd34fef646e7b38c338430bb/kombu/messaging.py#L234
we ask for the default channel and since it is not created and the https://github.com/celery/kombu/blob/2f5882331237147ccd34fef646e7b38c338430bb/kombu/connection.py#L957 call relies on transport options and not the retry policy.
> Update the transport options according to the retry policy

- requirements/extras/gcpubsub.txt
- google-cloud-pubsub version in versions larger than 2.20.3 raises the following error:
site-packages/google/protobuf/internal/well_known_types.py", line 443, in FromTimedelta
raise AttributeError(
AttributeError: Fail to convert to Duration.
Expected a timedelta like object got str: 'str' object has no attribute 'seconds'
Fix this by restriction of the allowed package versions.
> Fix: restrict google-cloud-pubsub version

- kombu/transport/sqlalchemy/__init__.py
- t/unit/transport/test_sqlalchemy.py
> Fix regression from #2148

- requirements/extras/gcpubsub.txt
Reverts celery/kombu#2168 due to https://github.com/celery/kombu/pull/2161#issuecomment-2421317654
@auvipy FYI
> Revert "Update google-cloud-pubsub requirement from <=2.20.3,>=2.18.4 to >=2.18.4,<=2.25.2"

- requirements/extras/gcpubsub.txt
- t/unit/transport/test_gcpubsub.py
- protobuf version in versions larger than 4.25.5 when used by google-cloud-pubsub raises the following error:
site-packages/google/protobuf/internal/well_known_types.py", line 443, in FromTimedelta
raise AttributeError(
AttributeError: Fail to convert to Duration.
Expected a timedelta like object got str: 'str' object has no attribute 'seconds'
Fix this by restriction of the allowed package versions
- Added unit test to validate pubsub and protobuf compatibility
- Enabled google-cloud-pubsub package versions bump
> Fix: restrict google protobuf version

- .github/workflows/linter.yml
- .github/workflows/python-package.yml
- t/unit/transport/test_redis.py
- tox.ini
Fixes https://github.com/celery/kombu/issues/2051.
> Add support for Python 3.13

- kombu/messaging.py
- t/unit/test_messaging.py
When publishing a message in confirm mode, there was no way to specify the confirmation timeout in `publish()`.
This PR adds a new `confirm_timeout` argument to address that.
> Added confirm_timeout argument to publish()

- docs/userguide/connections.rst
This PR adds documentation for three existing environment variables that control debug logging in Kombu.
> Add documentation for debug logs environment variables

- docs/userguide/connections.rst
This PR adds (incomplete) documentation for transport options of py-amqp.
> Add documentation for py-amqp transport options

- kombu/connection.py
- kombu/messaging.py
- t/integration/test_py_amqp.py
- t/unit/test_connection.py
- t/unit/test_pools.py
Fixes: https://github.com/celery/celery/issues/9259
When an amqp exception occurs while a connection is in use, the connection becomes unusable. Any attempts to use the connection can potentially block indefinitely.  
Currently, such broken connections are placed back into the connection pool, which causes a later `acquire` call on the pool to return a broken connection. 
See https://github.com/celery/celery/issues/9259
When a celery app is created with the `confirm_publish=True` option, it is possible for a celery task's `apply_async' method to block indefinitely if a broken connection is retrieved from the connection pool.
The `ProducerPool::acquire` and `ConnectionPool::acquire` method now return a wrapped `Connection/Producer`, that ensures the connections are properly closed in case …
> Close connections in case of an exception

- kombu/utils/url.py
- requirements/pkgutils.txt
- t/integration/test_redis.py
- t/unit/utils/test_url.py
!close #2210 
ssl_check_hostname is left as-is ("false"), and is evaluated to True when a Redis connection is created.
> fix: interpret the ssl_check_hostname as a boolean

- examples/delayed_infra.py
Hello!
I tried running the example code (`examples/delayed_infra.py`) because I wanted to better understand the newly added native delayed delivery.
However, I noticed that the generated example message was stuck in the `celery_delayed_1` queue.
After investigating, I found that there was no queue bound to `celery_delayed_delivery`. 
To resolve this, I declared the `destination` queue and set the appropriate routing key.
I hope this helps clarify things for others exploring the example code.
If I missed anything, please feel free to let me know! Thank you.
> Update delayed_infra example for better clarity

- AUTHORS
- kombu/asynchronous/aws/connection.py
- kombu/asynchronous/aws/sqs/connection.py
- kombu/transport/SQS.py
- t/unit/asynchronous/aws/sqs/test_connection.py
- t/unit/transport/test_SQS.py
@auvipy :wave: Hi there! There is no ticket for this issue -- I found this bug myself and thought I'd fix it.
---
Adds support for consuming botocore SQS `json` models in the SQS async code. This only affects consumer code.
Several parameters are supplied incorrectly as they have changed in the `query` to `json` botocore change. If you have a newer version of botocore, you will get the `json` service model instead of the old `query` model. I found several places where kombu was generating calls to the new `json` API  (indicated by the x-amz-json-1.0 content-type) but providing parameter names consistent with the `query` protocol.
This PR makes kombu aware of both the `json` and `query` protocol query names and provide them both. When the AWS request is later constructed from the service …
> SQS: Support Async JSON SQS Protocol & Message Attributes

- kombu/transport/native_delayed_delivery.py
- t/unit/transport/test_native_delayed_delivery.py
When a `Queue` is defined with the `bindings` parameter, calling `bind_queue_to_native_delayed_delivery_exchange` raises the following error:
```
File "kombu\transport\native_delayed_delivery.py", line 83, in bind_queue_to_native_delayed_delivery_exchange
exchange: Exchange = queue.exchange.bind(channel)
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'bind'
```
This happens because `queue.exchange` is `None` when the `Queue` is initialized with explicit `bindings`.
```
from kombu import Connection, Exchange, Queue, binding  
from kombu.transport.native_delayed_delivery import (  
bind_queue_to_native_delayed_delivery_exchange, calculate_routing_key,  
declare_native_delayed_delivery_exchanges_and_queues, level_name)  
with …
```
> Fix native_delayed_delivery for queue with explicit bindings

- kombu/asynchronous/aws/sqs/connection.py
- t/unit/asynchronous/aws/sqs/test_connection.py
Fixes #2257, which is from the error introduced by the JSON API patch in #2226.
Related: #2260
The lack of `Content-Type: application/x-www-form-urlencoded` prevented the SQS endpoint from getting the Action parameter from the body. 
I am still investigating exactly how/why that got dropped from my PR, but this is a patch that should unblock kombu consumers.
> SQS: Fix Query Protocol Content-Type header

- kombu/asynchronous/aws/sqs/connection.py
- t/unit/asynchronous/aws/sqs/test_connection.py
Adding more tests as requested in #2266.
I extended a few tests to also call `prepare()` and compare the final request attributes before they go over the network. 
This exposed a few issues where botocore does str-to-bytes comparison, which fails the test in pytest. I cleaned that up -- though it's worth noting that botocore is fairly lenient -- you can provide either str, bytes, a dict, or None. But for testing sanity I cleaned it up.
Verified this is working both with old versions of botocore and new versions.
> SQS: More Protocol Tests

- kombu/common.py
This addresses the issue I found after updating Kombu. Commit by commit, I identified 1686c35a063761f10f6391b57b06ee1383ef1259 as a source of problems.
This is just my quick attempt to fix the issue. What I still see as a problem is this convoluted code flow:
* (1) publish is called with retrying,
* (2) publish function tries to declare entities if they have not been declared yet,
* (3) declare is called with retrying too, instead of failing early because of the outer retry logic in publish,
* ---
* Closed channels/connections are passed down the stack as args/kwargs without any possibility to refresh them - logic in `Connection.ensure()` just passes args and kwargs to nested calls even if the object (or entity) itself is given a new connection.
This PR does not contain any tests. I am …
> Attempt to fix retry loop in `maybe_declare()` when broken connection

- kombu/asynchronous/semaphore.py
- requirements/default.txt
- requirements/pkgutils.txt
This PR moves all (one) usage of `typing_extensions` into a `if TYPE_CHECKING` block, so that the `typing-extensions` package is not required at runtime.
This might relate to #2281.
First-time contributor, sorry if I haven't followed the right contributing procedure.
> Move use of typing_extensions into TYPE_CHECKING block

- requirements/default.txt
Hello everyone,
I think we can safely upgrade tzdata to newer versions and do not require a version pin, because it is just a timezone database.
This will help other projects upgrading their dependencies without running into dependency conflicts.
Thanks
> Do not pin package tzdata anymore

- docs/userguide/pools.rst
just a typo in documentation about pools.use_global_limit
> Typo in pools's documentation

- kombu/transport/redis.py
- requirements/default.txt
> redis.connection.ConnectionPool API change: get_connection does not accept arguments

- kombu/transport/native_delayed_delivery.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> Resolve logger warnings

- kombu/transport/SQS.py
- t/unit/transport/test_SQS.py
This adds support for tagging SQS queues provisioned by Kombu. This helps with grouping/filtering queues and metrics reported from queues.
There is no existing issue this fixes, but I can create one if that is a requirement. It wasn't clear from the Contributing section in the README if it is.
> Allow setting `tags` in initial `boto3.sqs.create_queue` call via `transport_options`

- kombu/transport/SQS.py
@auvipy This PR corrects the documentation error introduced in merged PR [#2216](https://github.com/celery/kombu/pull/2216) where `sts_token_timeout` was incorrectly marked as "added in 5.6.0". The sts_token_timeout configuration option actually existed prior to version 5.6.0. Please merge this to fix the documentation
> Docs: Fix incorrect "added in 5.6.0" note for sts_token_timeout in SQS transport docs

- kombu/transport/mongodb.py
- t/unit/transport/test_mongodb.py
This PR fixes a failing test in test_mongodb_uri_parsing.test_replicaset_hosts caused by options retaining camelCase keys (replicaSet) and list values from uri_parser.parse_uri.
-     Added normalization step to lowercase all option keys and flatten single-item lists.
This restores expected behavior where options['replicaset'] == 'test_rs' and aligns with how Kombu handles other parsed URI options.
> Normalize mongodb options keys

- kombu/resource.py
This PR improves compatibility of Kombu with gevent. Removes custom `LifoQueue`.
Tradeoff: When shrinking down the pool, the most recently used item is removed first. However, I don't think the pool shrinking is called that much.
In recent gevent the LifoQueue is monkeypatched. In Kombu the type was implemented as deque, while in Python, Gevent, and Eventlet the queue is based on a list.
https://github.com/python/cpython/blob/3.13/Lib/queue.py#L304
https://github.com/Cue/eventlet/blob/master/eventlet/queue.py#L440
https://github.com/gevent/gevent/issues/2114
> Remove custom `LifoQueue` class conflicting with recent gevent

- .bumpversion.cfg
- Changelog.rst
- README.rst
- docs/includes/introduction.txt
- kombu/__init__.py
CI passes locally on Mac:
```console
3.13-unit: OK (221.86=setup[110.92]+cmd[110.94] seconds)
3.13-linux-integration-py-amqp: OK (215.55=setup[168.75]+cmd[46.81] seconds)
3.13-linux-integration-redis: OK (159.48=setup[139.54]+cmd[19.94] seconds)
3.13-linux-integration-mongodb: OK (443.21=setup[217.08]+cmd[226.14] seconds)
3.13-linux-integration-kafka: OK (219.04=setup[157.99]+cmd[61.06] seconds)
congratulations :) (443.82 seconds)
clean: OK (20.41=setup[17.92]+cmd[1.23,1.26] seconds)
lint: OK (90.73=setup[17.56]+cmd[73.17] seconds)
mypy: OK (86.94=setup[45.75]+cmd[41.19] seconds)
parallel: OK (467.09=setup[21.78]+cmd[445.31] seconds)
congratulations :) (467.78 seconds)
```
> Prepare for (pre) release: v5.6.0rc1
