celery/kombu

kombu/tests/transport/test_qpid.py, kombu/transport/qpid.py
Adjusts Qpid to use qpid.messaging exceptions instead of AMQP exceptions. The Qpid transport doesn't raise many exceptions so this is a pretty small fix. There were some lines that were too long, and a few variables and test names have been fixed up for clarity.
Now the behavior is like this:
```
>>> from kombu import Connection, Queue
>>> with Connection('qpid://localhost:5672') as connection:
...     with connection.channel() as channel:
...         q = Queue('dog', channel=channel)
...         q.purge()
... 
File "<stdin>", line 4, in <module>
File "/home/bmbouter/kombu/kombu/entity.py", line 583, in purge
nowait=nowait) or 0
File "/home/bmbouter/kombu/kombu/transport/qpid.py", line 798, in queue_purge
return self._purge(queue)
File …
```
=> Qpid raises a NotFound exception when a Queue doesn't exist

kombu/tests/transport/test_qpid.py, kombu/transport/qpid.py
This removes the QpidMessagingExceptionHandler and adds a simple exception catch to the one place that it was used. Also celery uses the pre-3.0 kombu error classes so this transport needs to continue to support those.
With this change I tested the following scenarios:
1) celery starts and waits for qpidd and successfully connects when it becomes available
2) celery is connected and qpidd dies. celery waits with the expected backoff behavior and when qpidd becomes available again it reconnects. This can happen any number of times stably.
3) same as (2) but qpidd is gracefully stopped and started
4) celery cannot authenticate. This is raised as an unrecoverable exception and it exits. That is the expected behavior.
=> Adds pre 3.0 error classes and removes a custom Exception handler

kombu/transport/zookeeper.py
The kazoo client already has the ability to use multiple
zookeeper servers as a comma separated list so instead of
sending only a single server in; send all the possible servers
and alternatives in to the client to let it natively handle
the servers to connect to.
=> Use multi-host support built-in to kazoo

kombu/transport/SQS.py
Add support for local SQS server, such as [fake_sqs](https://github.com/iain/fake_sqs).
=> allow custom regioninfo and port, is_secure options for SQS

kombu/transport/django/managers.py
=> #472 : Fix oracle exception

kombu/transport/mongodb.py
=> support pymongo 3.0

kombu/tests/transport/test_qpid.py, kombu/transport/qpid.py
Implements a workaround for celery/celery#3019
=> Implements late acking workaround

kombu/transport/qpid.py
=> Adds asynchronous error handling to Qpid transport

setup.cfg
=> Sync setup.cfg with requirements/default.txt

kombu/tests/transport/test_qpid.py, kombu/transport/qpid.py
=> Qpid Transport pipe usage is only for asynchronous operation

examples/hello_publisher.py
May be it is a spelling mistake
=> spelling mistake

kombu/tests/transport/test_SQS.py, kombu/transport/SQS.py
=> update queue cache in Channel before creating a new SQS queue

docs/userguide/examples.rst
http://docs.celeryproject.org/projects/kombu/en/latest/userguide/examples.html#task-queue-example remove useless code block after tasks.py
=> Fix useless code-block

docs/reference/kombu.transport.etcd.rst, kombu/tests/transport/test_etcd.py, kombu/transport/__init__.py, kombu/transport/etcd.py, requirements/extras/etcd.txt
This transport is highly influenced by the Consul Transport.
Messages are kept in keys within Etcd through the python-etcd library.
=> Add Etcd Transport

examples/memory_transport.py
This PR add a memory transport example and try to fix #606
=> memory transport example

kombu/transport/SQS.py
=> Update comments about SQS long polling.

kombu/messaging.py
=> Don't modify dict size while iterating over it

README.rst
=> Add syntax highlighting

kombu/transport/SQS.py
=> Fixing sqs drain_events issues

.travis.yml, appveyor.yml, tox.ini
Enabled pip cache for Travis CI
=> Add Python 3.6 to Travis CI testing

kombu/transport/redis.py, t/unit/transport/test_redis.py
=> Parse password from Redis transport URL

README.rst, docs/includes/introduction.txt, kombu/clocks.py, kombu/compat.py, kombu/serialization.py, kombu/transport/SQS.py, kombu/transport/librabbitmq.py, kombu/transport/mongodb.py, kombu/transport/qpid.py, kombu/utils/limits.py, setup.py
Just changed in comments and documentation.
=> Prefer https over http and updated links to new locations.

kombu/utils/compat.py
Seems a bit odd why the flake8 test doesn't highlight them.
=> E302 violations fixed

AUTHORS, Changelog, kombu/__init__.py
I've put together the Release Notes for `4.1.0`. I've omitted any small commits that wouldn't be particularly interesting to anyone unconcerned with PEP8 or bugs within our tests.
Please let me know if you have any concerns.
=> v4.1.0 Release

README.rst
This should have accompanied #764
=> Bump version in README

requirements/docs.txt
Let's make the build green again :)
=> Install sphinx_celery from git for now

requirements/extras/msgpack.txt
https://github.com/msgpack/msgpack-python#messagepack-for-python
=> msgpack package has been renamed

AUTHORS, kombu/transport/virtual/base.py, t/unit/transport/virtual/test_base.py
=> Virtual transport timeout does not supesede period polling

README.rst, docs/includes/introduction.txt
=> Fix rabbit and warrens link

kombu/transport/virtual/base.py
It should be a bit faster to use dict comprehensions.
=> Replaced a dict-construct with a dictionary comprehension.

.travis.yml, tox.ini
This repository have not reported coverage metrics to coveralls in over two years.
Time to fix that...
=> Always report coverage

README.rst
Fixed mailing list detail in Getting Help section
=> Fixed mailing list detail

Changelog
I've gone through the commits since the last tag and added them, grouping the minor tweaks/fixups and doc changes. I think I've got everything.
Incidentally I've left a question in #689 but that needn't prevent release.
=> Update Changelog for 4.2.0

setup.py
Fixes #881
Also add some blank lines for pep-8 compatibility
=> Remove data_files from setup.py

t/unit/test_connection.py
Added tests that verify that librabbitmq is selected when available and not selected when it is not available.
=> Increased test coverage for connection.py

kombu/compression.py, requirements/extras/brotli.txt, requirements/test-ci.txt, t/unit/test_compression.py
> Brotli is a generic-purpose lossless compression algorithm that compresses data using a combination of a modern variant of the LZ77 algorithm, Huffman coding and 2nd order context modeling, with a compression ratio comparable to the best currently available general-purpose compression methods. It is similar in speed with deflate but offers more dense compression.
We now allow users to use it if they want to.
=> Added optional support for brotli compression

Changelog
This is still work in progress but I'm nearly done.
I need to take another pass at the commit log, detail some of the changes and ensure all tests, cleanups and documentation contributions are attributed.
Please take a look and see if something is missing or incorrect.
=> 4.3 Changelog

kombu/transport/redis.py, t/unit/transport/test_redis.py
=> Use "_parse_url()" util to parse Sentinel master URL

docs/reference/index.rst, docs/reference/kombu.matcher.rst, kombu/matcher.py, kombu/pidbox.py, t/unit/test_matcher.py, t/unit/test_pidbox.py
rebase and small adjustments for matching logic based on #377
=> Control pattern matching

kombu/transport/redis.py, t/unit/transport/test_redis.py
=> make redis transport sep param configurable

kombu/common.py, t/unit/test_common.py
Reverts celery/kombu#906.
Fixes #1014
=> Revert "fix/Broadcast-fail-by-give-queue-kwargs"

requirements/extras/lzma.txt
This should in theory fix some of our build problems on Windows.
=> Added an index with windows wheels for lzma

kombu/transport/redis.py, kombu/transport/virtual/base.py, kombu/transport/virtual/exchange.py, t/unit/transport/test_redis.py
=> Revert "Use SIMEMBERS instead of SMEMBERS to check for queue (redis broker)"

kombu/asynchronous/aws/connection.py, t/unit/asynchronous/aws/test_connection.py
fixing https://github.com/celery/celery/issues/4988
=> return an empty list on SQS internal error.

.travis.yml, kombu/serialization.py, kombu/utils/uuid.py, requirements/default.txt
Reverts celery/kombu#1056
will readd for 4.7+
=> Revert "Use fastuuid on CPython>=3.5"

kombu/transport/redis.py, kombu/transport/virtual/base.py, kombu/transport/virtual/exchange.py, t/unit/transport/test_redis.py
=> Revert "Revert "Use SIMEMBERS instead of SMEMBERS to check for queue (redis broker)""

kombu/transport/redis.py, kombu/transport/virtual/base.py, kombu/transport/virtual/exchange.py, t/unit/transport/test_redis.py
=> Revert "Revert "Revert "Use SIMEMBERS instead of SMEMBERS to check for queue (redis broker)"""

kombu/asynchronous/hub.py, t/unit/asynchronous/test_hub.py
=> reset ready before execute callback

kombu/transport/redis.py
Solve to use redis service in aliyun, Brop in same slot error
=> fix brop must in same slot error

.travis.yml, kombu/transport/pyamqp.py, t/unit/transport/test_pyamqp.py
=> Travis CI: Fix travis validation issues

Changelog.rst
=> Added Release notes for 4.6.0 release.

kombu/transport/sqlalchemy/__init__.py
The init method for the SQLAlchemy transport's Channel implementation
is not currently thread-safe.
This means that if two threads in a process attempt to instantiate a
Channel concurrently, there can be a race condition when registering
the SQLAlchemy model classes, which leaves the SQLAlchemy ORM mapper
in a broken state.
This results in an exception like the following:
```
sqlalchemy.exc.InvalidRequestError: Table 'kombu_message' is already
defined for this MetaData instance.  Specify 'extend_existing=True' to
redefine options and columns on an existing Table object.
```
Any subsequent calls to the SQLAlchemy ORM will then fail with an
exception like this:
```
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path
"Message" in the registry of this declarative base. Please …
```
=> Fix: make SQLAlchemy Channel init thread-safe

kombu/transport/redis.py
=> Fix consumer encoding in Redis priority queues

kombu/common.py, t/unit/test_common.py
Reverts celery/kombu#1171. Fixes #1194
=> Revert "Raise RecoverableConnectionError in maybe_declare with retry "

kombu/common.py, t/unit/test_common.py
This PR is continuation of  #1171 and should fix #1194 .
PS. tested on celery master with this fix CI is fine. https://github.com/hzlmn/celery/runs/707223641
=> Fix connection imaybe_declare

kombu/connection.py, t/integration/common.py, t/integration/test_py_amqp.py, t/integration/test_redis.py, t/unit/test_connection.py, t/unit/transport/test_redis.py
=> Revert incompatible changes in #1193 and additional improvements

docs/userguide/failover.rst, docs/userguide/index.rst
This PR adds userguide covering Automatic Failover.
=> Added Failover userguide

kombu/transport/redis.py
=> Revert "Added redis transport key_prefix from envvars"

kombu/pidbox.py, t/unit/test_pidbox.py
This is the version of #1256 against master.
=> Fix pidbox not using default channels on master

requirements/extras/sqs.txt
=> Pin urllib3<1.26 to fix failing unittests.

kombu/messaging.py, t/unit/test_messaging.py
Continue to solve the problem https://github.com/celery/py-amqp/pull/343
=> Add timeout to producer publish

kombu/transport/redis.py, t/unit/transport/test_redis.py
Use the SentinelManagedSSLConnection when SSL is enabled for the
transport.
=> redis: Support Sentinel with SSL

docs/userguide/connections.rst
Add redis sentinel url example for connections.rst.
=> Update connections.rst with Redis sentinel example

docs/reference/kombu.transport.SQS.rst
SQS retry policy documentation improvement
=> SQS retry policy documentation improvement

AUTHORS, kombu/transport/redis.py, requirements/test.txt, t/unit/transport/test_redis.py
Reverts celery/kombu#1132
Fixes #1305
=> Revert "Port of redis code improvements from prior revision"

kombu/compression.py, t/unit/test_compression.py
=> Drop support for the lzma backport

docs/includes/introduction.txt
… at least I _think_ it's a mistake.
=> Fix tiny mistake in introduction

docs/userguide/consumers.rst
These are some minor issues I found when reading the documentation on consumers.
Mostly, these are text corrections (grammar, phrasing, structure), but there are a few fixes to code examples and I'd appreciate a second look at those.
It's not that I'm not confident in their correctness, but I haven't tested them and you'd know best, anyway.
=> Small doc fixes

.github/workflows/ci.yaml
This fixes the problem we have when we install system dependencies.
=> Fix CI failure

kombu/transport/qpid.py, kombu/utils/compat.py, t/unit/asynchronous/test_timer.py, t/unit/test_clocks.py, t/unit/transport/test_redis.py
=> Revert "chore: Refactor code quality issues"

kombu/transport/base.py
=> Fixed type comment

requirements/docs.txt
=> Fix missing dependency to redis in docs requirements

Changelog.rst
Final release notes for kombu 5.2.0
=> 5.2.0 release notes

kombu/transport/SQS.py, t/unit/transport/test_SQS.py
=> SQS transport: detect FIFO queue properly by checking queue URL

kombu/utils/compat.py
This should hopefully fix https://github.com/celery/kombu/issues/1339
Bear with me, I did this on my phone
=> Use new entry_points interface

.github/workflows/ci.yaml, kombu/utils/time.py, requirements/pkgutils.txt, setup.cfg, tox.ini
=> Add `mypy` to the pipeline

kombu/asynchronous/semaphore.py, requirements/default.txt, setup.cfg
=> chore: Annotate semaphore.py

kombu/__init__.py, kombu/asynchronous/aws/__init__.py, kombu/asynchronous/http/__init__.py, kombu/asynchronous/http/curl.py, kombu/asynchronous/hub.py, kombu/transport/__init__.py, kombu/utils/text.py, setup.cfg
=> Annotate init files

requirements/extras/consul.txt
https://github.com/celery/celery/pull/6544
=> move to consul2

kombu/matcher.py, setup.cfg
=> Annotate `matcher.py`

requirements/extras/confluentkafka.txt, setup.py
=> chore: add confluentkafka to extras 📌

kombu/transport/redis.py, t/integration/test_redis.py
=> Fix incompatibility with redis in disconnect()

kombu/transport/azureservicebus.py, kombu/transport/azurestoragequeues.py, requirements/extras/azurestoragequeues.txt, t/unit/transport/test_azurestoragequeues.py
The title is self-explanatory.
I added another commit because flake8 tests were failing.
=> add managed identity support to azure storage queue

kombu/transport/sqlalchemy/__init__.py, kombu/transport/sqlalchemy/models.py, requirements/test.txt
Changes required to get sqla 2.0 running.
I've tested these changes with 2.0 & 1.4
Fixes: #1609
=> support sqla v2.0

docs/userguide/serialization.rst
=> docs: Add notes for kombu.utils.json.register_type

.github/workflows/semgrep.yml
[Semgrep](https://semgrep.dev/) CI scan workflow.
=> Add Semgrep CI

examples/rpc-tut6/rpc_server.py
=>  moved shebang to python3

kombu/connection.py
#1755 did not remove the matching doc.
This PR completes it.
=> Doc fix (hotfix for #1755)

.pre-commit-config.yaml, kombu/messaging.py, kombu/serialization.py
Fix for issues raised due to upgrades added in #1772
=> Fixed pre-commit issues

docs/userguide/connections.rst
Kombu & celery with SQS #222 #1779
I have created this PR for better syntax.
=> syntax correction

.readthedocs.yaml, docs/conf.py
Basically copy & paste from Celery
=> Fix ReadTheDocs CI

Changelog.rst
=> Added Changelog for v5.3.5

requirements/funtest.txt
Matching other `boto3` requirements
=> boto3>=1.26.143

.github/workflows/ci.yaml
Let’s see if where we at with unit 3.9
=> Revert "Exclude Unit 3.9 from CI #2046"

requirements/default.txt
=> tzdata is required for machines without IANA database

.github/workflows/python-package.yml, tox.ini
Hi, Tom from Codecov here. I saw that you used Codecov already, and I thought you could benefit from catching any flaky or failed tests. We released a [Test Analytics](https://docs.codecov.com/docs/test-analytics) product that might be helpful and would love your feedback.
=> chore: add Codecov test analytics

.bumpversion.cfg, Changelog.rst, README.rst, docs/includes/introduction.txt, kombu/__init__.py
Run everything in parallel on a completely clean tox environment.
```bash
rm -rf .tox && tox -e clean,lint,mypy,parallel -p -o
```
```console
3.13-unit: OK (116.70=setup[60.55]+cmd[56.14] seconds)
3.13-linux-integration-py-amqp: OK (84.21=setup[68.06]+cmd[16.15] seconds)
3.13-linux-integration-redis: OK (83.78=setup[67.01]+cmd[16.77] seconds)
3.13-linux-integration-mongodb: OK (313.51=setup[90.83]+cmd[222.68] seconds)
3.13-linux-integration-kafka: OK (153.11=setup[114.41]+cmd[38.69] seconds)
congratulations :) (314.65 seconds)
clean: OK (13.25=setup[11.65]+cmd[0.87,0.72] seconds)
lint: OK (28.42=setup[11.30]+cmd[17.13] seconds)
mypy: OK (45.88=setup[29.56]+cmd[16.32] seconds)
parallel: OK (331.45=setup[15.12]+cmd[316.33] seconds)
congratulations :) (332.03 seconds)
```
=> Prepare for (pre) release: v5.6.0b3

.pre-commit-config.yaml, kombu/asynchronous/aws/ext.py
=> Bump mypy from 1.14.1 to 1.18.1 AGAIN
